/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[207] = {16, 12, 0, 16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[4] = {0, 1, 0, 0};
static const casadi_int casadi_s5[258] = {16, 15, 0, 16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s6[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s7[171] = {13, 12, 0, 13, 26, 39, 52, 65, 78, 91, 104, 117, 130, 143, 156, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s8[3] = {16, 0, 0};
static const casadi_int casadi_s9[3] = {13, 0, 0};

/* BAbt:(i0[12],i1[12],i2[12],i3[12],i4[3],i5[3],i6[12])->(o0[16x12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=arg[6]? arg[6][0] : 0;
  a1=arg[5]? arg[5][0] : 0;
  a2=(a0*a1);
  if (res[0]!=0) res[0][0]=a2;
  a2=0.;
  if (res[0]!=0) res[0][1]=a2;
  if (res[0]!=0) res[0][2]=a2;
  a3=arg[3]? arg[3][0] : 0;
  a4=(a0*a3);
  if (res[0]!=0) res[0][3]=a4;
  if (res[0]!=0) res[0][4]=a2;
  if (res[0]!=0) res[0][5]=a2;
  if (res[0]!=0) res[0][6]=a2;
  if (res[0]!=0) res[0][7]=a2;
  if (res[0]!=0) res[0][8]=a2;
  if (res[0]!=0) res[0][9]=a2;
  if (res[0]!=0) res[0][10]=a2;
  if (res[0]!=0) res[0][11]=a2;
  if (res[0]!=0) res[0][12]=a2;
  if (res[0]!=0) res[0][13]=a2;
  if (res[0]!=0) res[0][14]=a2;
  a4=arg[0]? arg[0][0] : 0;
  a5=arg[2]? arg[2][0] : 0;
  a3=(a3*a5);
  a5=arg[4]? arg[4][0] : 0;
  a1=(a1*a5);
  a3=(a3+a1);
  a0=(a0*a3);
  a4=(a4-a0);
  if (res[0]!=0) res[0][15]=a4;
  if (res[0]!=0) res[0][16]=a2;
  a4=arg[6]? arg[6][1] : 0;
  a0=arg[5]? arg[5][1] : 0;
  a3=(a4*a0);
  if (res[0]!=0) res[0][17]=a3;
  if (res[0]!=0) res[0][18]=a2;
  if (res[0]!=0) res[0][19]=a2;
  a3=arg[3]? arg[3][1] : 0;
  a1=(a4*a3);
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a2;
  if (res[0]!=0) res[0][22]=a2;
  if (res[0]!=0) res[0][23]=a2;
  if (res[0]!=0) res[0][24]=a2;
  if (res[0]!=0) res[0][25]=a2;
  if (res[0]!=0) res[0][26]=a2;
  if (res[0]!=0) res[0][27]=a2;
  if (res[0]!=0) res[0][28]=a2;
  if (res[0]!=0) res[0][29]=a2;
  if (res[0]!=0) res[0][30]=a2;
  a1=arg[0]? arg[0][1] : 0;
  a5=arg[2]? arg[2][1] : 0;
  a3=(a3*a5);
  a5=arg[4]? arg[4][1] : 0;
  a0=(a0*a5);
  a3=(a3+a0);
  a4=(a4*a3);
  a1=(a1-a4);
  if (res[0]!=0) res[0][31]=a1;
  if (res[0]!=0) res[0][32]=a2;
  if (res[0]!=0) res[0][33]=a2;
  a1=arg[6]? arg[6][2] : 0;
  a4=arg[5]? arg[5][2] : 0;
  a3=(a1*a4);
  if (res[0]!=0) res[0][34]=a3;
  if (res[0]!=0) res[0][35]=a2;
  if (res[0]!=0) res[0][36]=a2;
  a3=arg[3]? arg[3][2] : 0;
  a0=(a1*a3);
  if (res[0]!=0) res[0][37]=a0;
  if (res[0]!=0) res[0][38]=a2;
  if (res[0]!=0) res[0][39]=a2;
  if (res[0]!=0) res[0][40]=a2;
  if (res[0]!=0) res[0][41]=a2;
  if (res[0]!=0) res[0][42]=a2;
  if (res[0]!=0) res[0][43]=a2;
  if (res[0]!=0) res[0][44]=a2;
  if (res[0]!=0) res[0][45]=a2;
  if (res[0]!=0) res[0][46]=a2;
  a0=arg[0]? arg[0][2] : 0;
  a5=arg[2]? arg[2][2] : 0;
  a3=(a3*a5);
  a5=arg[4]? arg[4][2] : 0;
  a4=(a4*a5);
  a3=(a3+a4);
  a1=(a1*a3);
  a0=(a0-a1);
  if (res[0]!=0) res[0][47]=a0;
  if (res[0]!=0) res[0][48]=a2;
  if (res[0]!=0) res[0][49]=a2;
  if (res[0]!=0) res[0][50]=a2;
  if (res[0]!=0) res[0][51]=a2;
  if (res[0]!=0) res[0][52]=a2;
  if (res[0]!=0) res[0][53]=a2;
  a0=arg[6]? arg[6][3] : 0;
  a1=arg[3]? arg[3][3] : 0;
  a3=(a0*a1);
  if (res[0]!=0) res[0][54]=a3;
  if (res[0]!=0) res[0][55]=a2;
  if (res[0]!=0) res[0][56]=a2;
  if (res[0]!=0) res[0][57]=a2;
  if (res[0]!=0) res[0][58]=a2;
  if (res[0]!=0) res[0][59]=a2;
  if (res[0]!=0) res[0][60]=a2;
  if (res[0]!=0) res[0][61]=a2;
  if (res[0]!=0) res[0][62]=a2;
  a3=arg[0]? arg[0][3] : 0;
  a4=arg[2]? arg[2][3] : 0;
  a1=(a1*a4);
  a0=(a0*a1);
  a3=(a3-a0);
  if (res[0]!=0) res[0][63]=a3;
  if (res[0]!=0) res[0][64]=a2;
  if (res[0]!=0) res[0][65]=a2;
  if (res[0]!=0) res[0][66]=a2;
  if (res[0]!=0) res[0][67]=a2;
  if (res[0]!=0) res[0][68]=a2;
  if (res[0]!=0) res[0][69]=a2;
  if (res[0]!=0) res[0][70]=a2;
  a3=arg[6]? arg[6][4] : 0;
  a0=arg[3]? arg[3][4] : 0;
  a1=(a3*a0);
  if (res[0]!=0) res[0][71]=a1;
  if (res[0]!=0) res[0][72]=a2;
  if (res[0]!=0) res[0][73]=a2;
  if (res[0]!=0) res[0][74]=a2;
  if (res[0]!=0) res[0][75]=a2;
  if (res[0]!=0) res[0][76]=a2;
  if (res[0]!=0) res[0][77]=a2;
  if (res[0]!=0) res[0][78]=a2;
  a1=arg[0]? arg[0][4] : 0;
  a4=arg[2]? arg[2][4] : 0;
  a0=(a0*a4);
  a3=(a3*a0);
  a1=(a1-a3);
  if (res[0]!=0) res[0][79]=a1;
  if (res[0]!=0) res[0][80]=a2;
  if (res[0]!=0) res[0][81]=a2;
  if (res[0]!=0) res[0][82]=a2;
  if (res[0]!=0) res[0][83]=a2;
  if (res[0]!=0) res[0][84]=a2;
  if (res[0]!=0) res[0][85]=a2;
  if (res[0]!=0) res[0][86]=a2;
  if (res[0]!=0) res[0][87]=a2;
  a1=arg[6]? arg[6][5] : 0;
  a3=arg[3]? arg[3][5] : 0;
  a0=(a1*a3);
  if (res[0]!=0) res[0][88]=a0;
  if (res[0]!=0) res[0][89]=a2;
  if (res[0]!=0) res[0][90]=a2;
  if (res[0]!=0) res[0][91]=a2;
  if (res[0]!=0) res[0][92]=a2;
  if (res[0]!=0) res[0][93]=a2;
  if (res[0]!=0) res[0][94]=a2;
  a0=arg[0]? arg[0][5] : 0;
  a4=arg[2]? arg[2][5] : 0;
  a3=(a3*a4);
  a1=(a1*a3);
  a0=(a0-a1);
  if (res[0]!=0) res[0][95]=a0;
  if (res[0]!=0) res[0][96]=a2;
  if (res[0]!=0) res[0][97]=a2;
  if (res[0]!=0) res[0][98]=a2;
  if (res[0]!=0) res[0][99]=a2;
  if (res[0]!=0) res[0][100]=a2;
  if (res[0]!=0) res[0][101]=a2;
  if (res[0]!=0) res[0][102]=a2;
  if (res[0]!=0) res[0][103]=a2;
  if (res[0]!=0) res[0][104]=a2;
  a0=arg[6]? arg[6][6] : 0;
  a1=arg[3]? arg[3][6] : 0;
  a3=(a0*a1);
  if (res[0]!=0) res[0][105]=a3;
  if (res[0]!=0) res[0][106]=a2;
  if (res[0]!=0) res[0][107]=a2;
  if (res[0]!=0) res[0][108]=a2;
  if (res[0]!=0) res[0][109]=a2;
  if (res[0]!=0) res[0][110]=a2;
  a3=arg[0]? arg[0][6] : 0;
  a4=arg[2]? arg[2][6] : 0;
  a1=(a1*a4);
  a0=(a0*a1);
  a3=(a3-a0);
  if (res[0]!=0) res[0][111]=a3;
  if (res[0]!=0) res[0][112]=a2;
  if (res[0]!=0) res[0][113]=a2;
  if (res[0]!=0) res[0][114]=a2;
  if (res[0]!=0) res[0][115]=a2;
  if (res[0]!=0) res[0][116]=a2;
  if (res[0]!=0) res[0][117]=a2;
  if (res[0]!=0) res[0][118]=a2;
  if (res[0]!=0) res[0][119]=a2;
  if (res[0]!=0) res[0][120]=a2;
  if (res[0]!=0) res[0][121]=a2;
  a3=arg[6]? arg[6][7] : 0;
  a0=arg[3]? arg[3][7] : 0;
  a1=(a3*a0);
  if (res[0]!=0) res[0][122]=a1;
  if (res[0]!=0) res[0][123]=a2;
  if (res[0]!=0) res[0][124]=a2;
  if (res[0]!=0) res[0][125]=a2;
  if (res[0]!=0) res[0][126]=a2;
  a1=arg[0]? arg[0][7] : 0;
  a4=arg[2]? arg[2][7] : 0;
  a0=(a0*a4);
  a3=(a3*a0);
  a1=(a1-a3);
  if (res[0]!=0) res[0][127]=a1;
  if (res[0]!=0) res[0][128]=a2;
  if (res[0]!=0) res[0][129]=a2;
  if (res[0]!=0) res[0][130]=a2;
  if (res[0]!=0) res[0][131]=a2;
  if (res[0]!=0) res[0][132]=a2;
  if (res[0]!=0) res[0][133]=a2;
  if (res[0]!=0) res[0][134]=a2;
  if (res[0]!=0) res[0][135]=a2;
  if (res[0]!=0) res[0][136]=a2;
  if (res[0]!=0) res[0][137]=a2;
  if (res[0]!=0) res[0][138]=a2;
  a1=arg[6]? arg[6][8] : 0;
  a3=arg[3]? arg[3][8] : 0;
  a0=(a1*a3);
  if (res[0]!=0) res[0][139]=a0;
  if (res[0]!=0) res[0][140]=a2;
  if (res[0]!=0) res[0][141]=a2;
  if (res[0]!=0) res[0][142]=a2;
  a0=arg[0]? arg[0][8] : 0;
  a4=arg[2]? arg[2][8] : 0;
  a3=(a3*a4);
  a1=(a1*a3);
  a0=(a0-a1);
  if (res[0]!=0) res[0][143]=a0;
  if (res[0]!=0) res[0][144]=a2;
  if (res[0]!=0) res[0][145]=a2;
  if (res[0]!=0) res[0][146]=a2;
  if (res[0]!=0) res[0][147]=a2;
  if (res[0]!=0) res[0][148]=a2;
  if (res[0]!=0) res[0][149]=a2;
  if (res[0]!=0) res[0][150]=a2;
  if (res[0]!=0) res[0][151]=a2;
  if (res[0]!=0) res[0][152]=a2;
  if (res[0]!=0) res[0][153]=a2;
  if (res[0]!=0) res[0][154]=a2;
  if (res[0]!=0) res[0][155]=a2;
  a0=arg[6]? arg[6][9] : 0;
  a1=arg[3]? arg[3][9] : 0;
  a3=(a0*a1);
  if (res[0]!=0) res[0][156]=a3;
  if (res[0]!=0) res[0][157]=a2;
  if (res[0]!=0) res[0][158]=a2;
  a3=arg[0]? arg[0][9] : 0;
  a4=arg[2]? arg[2][9] : 0;
  a1=(a1*a4);
  a0=(a0*a1);
  a3=(a3-a0);
  if (res[0]!=0) res[0][159]=a3;
  if (res[0]!=0) res[0][160]=a2;
  if (res[0]!=0) res[0][161]=a2;
  if (res[0]!=0) res[0][162]=a2;
  if (res[0]!=0) res[0][163]=a2;
  if (res[0]!=0) res[0][164]=a2;
  if (res[0]!=0) res[0][165]=a2;
  if (res[0]!=0) res[0][166]=a2;
  if (res[0]!=0) res[0][167]=a2;
  if (res[0]!=0) res[0][168]=a2;
  if (res[0]!=0) res[0][169]=a2;
  if (res[0]!=0) res[0][170]=a2;
  if (res[0]!=0) res[0][171]=a2;
  if (res[0]!=0) res[0][172]=a2;
  a3=arg[6]? arg[6][10] : 0;
  a0=arg[3]? arg[3][10] : 0;
  a1=(a3*a0);
  if (res[0]!=0) res[0][173]=a1;
  if (res[0]!=0) res[0][174]=a2;
  a1=arg[0]? arg[0][10] : 0;
  a4=arg[2]? arg[2][10] : 0;
  a0=(a0*a4);
  a3=(a3*a0);
  a1=(a1-a3);
  if (res[0]!=0) res[0][175]=a1;
  if (res[0]!=0) res[0][176]=a2;
  if (res[0]!=0) res[0][177]=a2;
  if (res[0]!=0) res[0][178]=a2;
  if (res[0]!=0) res[0][179]=a2;
  if (res[0]!=0) res[0][180]=a2;
  if (res[0]!=0) res[0][181]=a2;
  if (res[0]!=0) res[0][182]=a2;
  if (res[0]!=0) res[0][183]=a2;
  if (res[0]!=0) res[0][184]=a2;
  if (res[0]!=0) res[0][185]=a2;
  if (res[0]!=0) res[0][186]=a2;
  if (res[0]!=0) res[0][187]=a2;
  if (res[0]!=0) res[0][188]=a2;
  if (res[0]!=0) res[0][189]=a2;
  a2=arg[6]? arg[6][11] : 0;
  a1=arg[3]? arg[3][11] : 0;
  a3=(a2*a1);
  if (res[0]!=0) res[0][190]=a3;
  a3=arg[0]? arg[0][11] : 0;
  a0=arg[2]? arg[2][11] : 0;
  a1=(a1*a0);
  a2=(a2*a1);
  a3=(a3-a2);
  if (res[0]!=0) res[0][191]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int BAbt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int BAbt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int BAbt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BAbt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int BAbt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BAbt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void BAbt_incref(void) {
}

CASADI_SYMBOL_EXPORT void BAbt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int BAbt_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int BAbt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real BAbt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BAbt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BAbt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BAbt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s1;
    case 5: return casadi_s1;
    case 6: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BAbt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int BAbt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* bk:(i0[12],i1[12],i2[12],i3[12],i4[3],i5[3],i6[12])->(o0[12]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[6]? arg[6][0] : 0;
  a2=arg[3]? arg[3][0] : 0;
  a3=arg[2]? arg[2][0] : 0;
  a2=(a2*a3);
  a3=arg[5]? arg[5][0] : 0;
  a4=arg[4]? arg[4][0] : 0;
  a3=(a3*a4);
  a2=(a2+a3);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  a1=arg[6]? arg[6][1] : 0;
  a2=arg[3]? arg[3][1] : 0;
  a3=arg[2]? arg[2][1] : 0;
  a2=(a2*a3);
  a3=arg[5]? arg[5][1] : 0;
  a4=arg[4]? arg[4][1] : 0;
  a3=(a3*a4);
  a2=(a2+a3);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a1=arg[6]? arg[6][2] : 0;
  a2=arg[3]? arg[3][2] : 0;
  a3=arg[2]? arg[2][2] : 0;
  a2=(a2*a3);
  a3=arg[5]? arg[5][2] : 0;
  a4=arg[4]? arg[4][2] : 0;
  a3=(a3*a4);
  a2=(a2+a3);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[6]? arg[6][3] : 0;
  a2=arg[3]? arg[3][3] : 0;
  a3=arg[2]? arg[2][3] : 0;
  a2=(a2*a3);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[0]? arg[0][4] : 0;
  a1=arg[6]? arg[6][4] : 0;
  a2=arg[3]? arg[3][4] : 0;
  a3=arg[2]? arg[2][4] : 0;
  a2=(a2*a3);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[0]? arg[0][5] : 0;
  a1=arg[6]? arg[6][5] : 0;
  a2=arg[3]? arg[3][5] : 0;
  a3=arg[2]? arg[2][5] : 0;
  a2=(a2*a3);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[0]? arg[0][6] : 0;
  a1=arg[6]? arg[6][6] : 0;
  a2=arg[3]? arg[3][6] : 0;
  a3=arg[2]? arg[2][6] : 0;
  a2=(a2*a3);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[0]? arg[0][7] : 0;
  a1=arg[6]? arg[6][7] : 0;
  a2=arg[3]? arg[3][7] : 0;
  a3=arg[2]? arg[2][7] : 0;
  a2=(a2*a3);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[0]? arg[0][8] : 0;
  a1=arg[6]? arg[6][8] : 0;
  a2=arg[3]? arg[3][8] : 0;
  a3=arg[2]? arg[2][8] : 0;
  a2=(a2*a3);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[0]? arg[0][9] : 0;
  a1=arg[6]? arg[6][9] : 0;
  a2=arg[3]? arg[3][9] : 0;
  a3=arg[2]? arg[2][9] : 0;
  a2=(a2*a3);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[0]? arg[0][10] : 0;
  a1=arg[6]? arg[6][10] : 0;
  a2=arg[3]? arg[3][10] : 0;
  a3=arg[2]? arg[2][10] : 0;
  a2=(a2*a3);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[0]? arg[0][11] : 0;
  a1=arg[6]? arg[6][11] : 0;
  a2=arg[3]? arg[3][11] : 0;
  a3=arg[2]? arg[2][11] : 0;
  a2=(a2*a3);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][11]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bk(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bk_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bk_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bk_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bk_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bk_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bk_incref(void) {
}

CASADI_SYMBOL_EXPORT void bk_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bk_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int bk_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bk_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bk_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bk_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bk_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s1;
    case 5: return casadi_s1;
    case 6: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bk_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bk_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* RSQrqtI:(i0,i1[12],i2[12],i3[3],i4[3],i5[12],i6[12],i7[0],i8[0])->(o0[16x15]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[4]? arg[4][0] : 0;
  a1=arg[0]? arg[0][0] : 0;
  a2=(a0+a0);
  a2=(a1*a2);
  a2=(a0*a2);
  if (res[0]!=0) res[0][0]=a2;
  a2=0.;
  if (res[0]!=0) res[0][1]=a2;
  if (res[0]!=0) res[0][2]=a2;
  if (res[0]!=0) res[0][3]=a2;
  if (res[0]!=0) res[0][4]=a2;
  if (res[0]!=0) res[0][5]=a2;
  if (res[0]!=0) res[0][6]=a2;
  if (res[0]!=0) res[0][7]=a2;
  if (res[0]!=0) res[0][8]=a2;
  if (res[0]!=0) res[0][9]=a2;
  if (res[0]!=0) res[0][10]=a2;
  if (res[0]!=0) res[0][11]=a2;
  if (res[0]!=0) res[0][12]=a2;
  if (res[0]!=0) res[0][13]=a2;
  if (res[0]!=0) res[0][14]=a2;
  a3=arg[3]? arg[3][0] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][15]=a0;
  if (res[0]!=0) res[0][16]=a2;
  a0=arg[4]? arg[4][1] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][17]=a3;
  if (res[0]!=0) res[0][18]=a2;
  if (res[0]!=0) res[0][19]=a2;
  if (res[0]!=0) res[0][20]=a2;
  if (res[0]!=0) res[0][21]=a2;
  if (res[0]!=0) res[0][22]=a2;
  if (res[0]!=0) res[0][23]=a2;
  if (res[0]!=0) res[0][24]=a2;
  if (res[0]!=0) res[0][25]=a2;
  if (res[0]!=0) res[0][26]=a2;
  if (res[0]!=0) res[0][27]=a2;
  if (res[0]!=0) res[0][28]=a2;
  if (res[0]!=0) res[0][29]=a2;
  if (res[0]!=0) res[0][30]=a2;
  a3=arg[3]? arg[3][1] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a2;
  if (res[0]!=0) res[0][33]=a2;
  a0=arg[4]? arg[4][2] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][34]=a3;
  if (res[0]!=0) res[0][35]=a2;
  if (res[0]!=0) res[0][36]=a2;
  if (res[0]!=0) res[0][37]=a2;
  if (res[0]!=0) res[0][38]=a2;
  if (res[0]!=0) res[0][39]=a2;
  if (res[0]!=0) res[0][40]=a2;
  if (res[0]!=0) res[0][41]=a2;
  if (res[0]!=0) res[0][42]=a2;
  if (res[0]!=0) res[0][43]=a2;
  if (res[0]!=0) res[0][44]=a2;
  if (res[0]!=0) res[0][45]=a2;
  if (res[0]!=0) res[0][46]=a2;
  a3=arg[3]? arg[3][2] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][47]=a0;
  if (res[0]!=0) res[0][48]=a2;
  if (res[0]!=0) res[0][49]=a2;
  if (res[0]!=0) res[0][50]=a2;
  a0=arg[2]? arg[2][0] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][51]=a3;
  if (res[0]!=0) res[0][52]=a2;
  if (res[0]!=0) res[0][53]=a2;
  if (res[0]!=0) res[0][54]=a2;
  if (res[0]!=0) res[0][55]=a2;
  if (res[0]!=0) res[0][56]=a2;
  if (res[0]!=0) res[0][57]=a2;
  if (res[0]!=0) res[0][58]=a2;
  if (res[0]!=0) res[0][59]=a2;
  if (res[0]!=0) res[0][60]=a2;
  if (res[0]!=0) res[0][61]=a2;
  if (res[0]!=0) res[0][62]=a2;
  a3=arg[1]? arg[1][0] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][63]=a0;
  if (res[0]!=0) res[0][64]=a2;
  if (res[0]!=0) res[0][65]=a2;
  if (res[0]!=0) res[0][66]=a2;
  if (res[0]!=0) res[0][67]=a2;
  a0=arg[2]? arg[2][1] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][68]=a3;
  if (res[0]!=0) res[0][69]=a2;
  if (res[0]!=0) res[0][70]=a2;
  if (res[0]!=0) res[0][71]=a2;
  if (res[0]!=0) res[0][72]=a2;
  if (res[0]!=0) res[0][73]=a2;
  if (res[0]!=0) res[0][74]=a2;
  if (res[0]!=0) res[0][75]=a2;
  if (res[0]!=0) res[0][76]=a2;
  if (res[0]!=0) res[0][77]=a2;
  if (res[0]!=0) res[0][78]=a2;
  a3=arg[1]? arg[1][1] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][79]=a0;
  if (res[0]!=0) res[0][80]=a2;
  if (res[0]!=0) res[0][81]=a2;
  if (res[0]!=0) res[0][82]=a2;
  if (res[0]!=0) res[0][83]=a2;
  if (res[0]!=0) res[0][84]=a2;
  a0=arg[2]? arg[2][2] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][85]=a3;
  if (res[0]!=0) res[0][86]=a2;
  if (res[0]!=0) res[0][87]=a2;
  if (res[0]!=0) res[0][88]=a2;
  if (res[0]!=0) res[0][89]=a2;
  if (res[0]!=0) res[0][90]=a2;
  if (res[0]!=0) res[0][91]=a2;
  if (res[0]!=0) res[0][92]=a2;
  if (res[0]!=0) res[0][93]=a2;
  if (res[0]!=0) res[0][94]=a2;
  a3=arg[1]? arg[1][2] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][95]=a0;
  if (res[0]!=0) res[0][96]=a2;
  if (res[0]!=0) res[0][97]=a2;
  if (res[0]!=0) res[0][98]=a2;
  if (res[0]!=0) res[0][99]=a2;
  if (res[0]!=0) res[0][100]=a2;
  if (res[0]!=0) res[0][101]=a2;
  a0=arg[2]? arg[2][3] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][102]=a3;
  if (res[0]!=0) res[0][103]=a2;
  if (res[0]!=0) res[0][104]=a2;
  if (res[0]!=0) res[0][105]=a2;
  if (res[0]!=0) res[0][106]=a2;
  if (res[0]!=0) res[0][107]=a2;
  if (res[0]!=0) res[0][108]=a2;
  if (res[0]!=0) res[0][109]=a2;
  if (res[0]!=0) res[0][110]=a2;
  a3=arg[1]? arg[1][3] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][111]=a0;
  if (res[0]!=0) res[0][112]=a2;
  if (res[0]!=0) res[0][113]=a2;
  if (res[0]!=0) res[0][114]=a2;
  if (res[0]!=0) res[0][115]=a2;
  if (res[0]!=0) res[0][116]=a2;
  if (res[0]!=0) res[0][117]=a2;
  if (res[0]!=0) res[0][118]=a2;
  a0=arg[2]? arg[2][4] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][119]=a3;
  if (res[0]!=0) res[0][120]=a2;
  if (res[0]!=0) res[0][121]=a2;
  if (res[0]!=0) res[0][122]=a2;
  if (res[0]!=0) res[0][123]=a2;
  if (res[0]!=0) res[0][124]=a2;
  if (res[0]!=0) res[0][125]=a2;
  if (res[0]!=0) res[0][126]=a2;
  a3=arg[1]? arg[1][4] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][127]=a0;
  if (res[0]!=0) res[0][128]=a2;
  if (res[0]!=0) res[0][129]=a2;
  if (res[0]!=0) res[0][130]=a2;
  if (res[0]!=0) res[0][131]=a2;
  if (res[0]!=0) res[0][132]=a2;
  if (res[0]!=0) res[0][133]=a2;
  if (res[0]!=0) res[0][134]=a2;
  if (res[0]!=0) res[0][135]=a2;
  a0=arg[2]? arg[2][5] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][136]=a3;
  if (res[0]!=0) res[0][137]=a2;
  if (res[0]!=0) res[0][138]=a2;
  if (res[0]!=0) res[0][139]=a2;
  if (res[0]!=0) res[0][140]=a2;
  if (res[0]!=0) res[0][141]=a2;
  if (res[0]!=0) res[0][142]=a2;
  a3=arg[1]? arg[1][5] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][143]=a0;
  if (res[0]!=0) res[0][144]=a2;
  if (res[0]!=0) res[0][145]=a2;
  if (res[0]!=0) res[0][146]=a2;
  if (res[0]!=0) res[0][147]=a2;
  if (res[0]!=0) res[0][148]=a2;
  if (res[0]!=0) res[0][149]=a2;
  if (res[0]!=0) res[0][150]=a2;
  if (res[0]!=0) res[0][151]=a2;
  if (res[0]!=0) res[0][152]=a2;
  a0=arg[2]? arg[2][6] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][153]=a3;
  if (res[0]!=0) res[0][154]=a2;
  if (res[0]!=0) res[0][155]=a2;
  if (res[0]!=0) res[0][156]=a2;
  if (res[0]!=0) res[0][157]=a2;
  if (res[0]!=0) res[0][158]=a2;
  a3=arg[1]? arg[1][6] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][159]=a0;
  if (res[0]!=0) res[0][160]=a2;
  if (res[0]!=0) res[0][161]=a2;
  if (res[0]!=0) res[0][162]=a2;
  if (res[0]!=0) res[0][163]=a2;
  if (res[0]!=0) res[0][164]=a2;
  if (res[0]!=0) res[0][165]=a2;
  if (res[0]!=0) res[0][166]=a2;
  if (res[0]!=0) res[0][167]=a2;
  if (res[0]!=0) res[0][168]=a2;
  if (res[0]!=0) res[0][169]=a2;
  a0=arg[2]? arg[2][7] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][170]=a3;
  if (res[0]!=0) res[0][171]=a2;
  if (res[0]!=0) res[0][172]=a2;
  if (res[0]!=0) res[0][173]=a2;
  if (res[0]!=0) res[0][174]=a2;
  a3=arg[1]? arg[1][7] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][175]=a0;
  if (res[0]!=0) res[0][176]=a2;
  if (res[0]!=0) res[0][177]=a2;
  if (res[0]!=0) res[0][178]=a2;
  if (res[0]!=0) res[0][179]=a2;
  if (res[0]!=0) res[0][180]=a2;
  if (res[0]!=0) res[0][181]=a2;
  if (res[0]!=0) res[0][182]=a2;
  if (res[0]!=0) res[0][183]=a2;
  if (res[0]!=0) res[0][184]=a2;
  if (res[0]!=0) res[0][185]=a2;
  if (res[0]!=0) res[0][186]=a2;
  a0=arg[2]? arg[2][8] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][187]=a3;
  if (res[0]!=0) res[0][188]=a2;
  if (res[0]!=0) res[0][189]=a2;
  if (res[0]!=0) res[0][190]=a2;
  a3=arg[1]? arg[1][8] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][191]=a0;
  if (res[0]!=0) res[0][192]=a2;
  if (res[0]!=0) res[0][193]=a2;
  if (res[0]!=0) res[0][194]=a2;
  if (res[0]!=0) res[0][195]=a2;
  if (res[0]!=0) res[0][196]=a2;
  if (res[0]!=0) res[0][197]=a2;
  if (res[0]!=0) res[0][198]=a2;
  if (res[0]!=0) res[0][199]=a2;
  if (res[0]!=0) res[0][200]=a2;
  if (res[0]!=0) res[0][201]=a2;
  if (res[0]!=0) res[0][202]=a2;
  if (res[0]!=0) res[0][203]=a2;
  a0=arg[2]? arg[2][9] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][204]=a3;
  if (res[0]!=0) res[0][205]=a2;
  if (res[0]!=0) res[0][206]=a2;
  a3=arg[1]? arg[1][9] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][207]=a0;
  if (res[0]!=0) res[0][208]=a2;
  if (res[0]!=0) res[0][209]=a2;
  if (res[0]!=0) res[0][210]=a2;
  if (res[0]!=0) res[0][211]=a2;
  if (res[0]!=0) res[0][212]=a2;
  if (res[0]!=0) res[0][213]=a2;
  if (res[0]!=0) res[0][214]=a2;
  if (res[0]!=0) res[0][215]=a2;
  if (res[0]!=0) res[0][216]=a2;
  if (res[0]!=0) res[0][217]=a2;
  if (res[0]!=0) res[0][218]=a2;
  if (res[0]!=0) res[0][219]=a2;
  if (res[0]!=0) res[0][220]=a2;
  a0=arg[2]? arg[2][10] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][221]=a3;
  if (res[0]!=0) res[0][222]=a2;
  a3=arg[1]? arg[1][10] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][223]=a0;
  if (res[0]!=0) res[0][224]=a2;
  if (res[0]!=0) res[0][225]=a2;
  if (res[0]!=0) res[0][226]=a2;
  if (res[0]!=0) res[0][227]=a2;
  if (res[0]!=0) res[0][228]=a2;
  if (res[0]!=0) res[0][229]=a2;
  if (res[0]!=0) res[0][230]=a2;
  if (res[0]!=0) res[0][231]=a2;
  if (res[0]!=0) res[0][232]=a2;
  if (res[0]!=0) res[0][233]=a2;
  if (res[0]!=0) res[0][234]=a2;
  if (res[0]!=0) res[0][235]=a2;
  if (res[0]!=0) res[0][236]=a2;
  if (res[0]!=0) res[0][237]=a2;
  a2=arg[2]? arg[2][11] : 0;
  a0=(a2+a2);
  a0=(a1*a0);
  a0=(a2*a0);
  if (res[0]!=0) res[0][238]=a0;
  a0=arg[1]? arg[1][11] : 0;
  a0=(a2*a0);
  a0=(a0+a0);
  a0=(a0*a1);
  a2=(a2*a0);
  if (res[0]!=0) res[0][239]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int RSQrqtI_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtI_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtI_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int RSQrqtI_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtI_release(int mem) {
}

CASADI_SYMBOL_EXPORT void RSQrqtI_incref(void) {
}

CASADI_SYMBOL_EXPORT void RSQrqtI_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtI_n_in(void) { return 9;}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtI_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real RSQrqtI_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtI_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtI_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtI_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s4;
    case 8: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtI_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int RSQrqtI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* rqI:(i0,i1[12],i2[12],i3[3],i4[3],i5[12],i6[0])->(o0[15]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=arg[4]? arg[4][0] : 0;
  a1=arg[3]? arg[3][0] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a2=arg[0]? arg[0][0] : 0;
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[4]? arg[4][1] : 0;
  a1=arg[3]? arg[3][1] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[4]? arg[4][2] : 0;
  a1=arg[3]? arg[3][2] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[2]? arg[2][0] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[2]? arg[2][1] : 0;
  a1=arg[1]? arg[1][1] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[2]? arg[2][2] : 0;
  a1=arg[1]? arg[1][2] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[2]? arg[2][3] : 0;
  a1=arg[1]? arg[1][3] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[2]? arg[2][4] : 0;
  a1=arg[1]? arg[1][4] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[2]? arg[2][5] : 0;
  a1=arg[1]? arg[1][5] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[2]? arg[2][6] : 0;
  a1=arg[1]? arg[1][6] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[2]? arg[2][7] : 0;
  a1=arg[1]? arg[1][7] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[2]? arg[2][8] : 0;
  a1=arg[1]? arg[1][8] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[2]? arg[2][9] : 0;
  a1=arg[1]? arg[1][9] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][12]=a0;
  a0=arg[2]? arg[2][10] : 0;
  a1=arg[1]? arg[1][10] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][13]=a0;
  a0=arg[2]? arg[2][11] : 0;
  a1=arg[1]? arg[1][11] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][14]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rqI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rqI_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rqI_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqI_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rqI_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqI_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rqI_incref(void) {
}

CASADI_SYMBOL_EXPORT void rqI_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rqI_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int rqI_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rqI_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqI_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqI_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqI_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s0;
    case 6: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqI_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rqI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* RSQrqt:(i0,i1[12],i2[12],i3[3],i4[3],i5[12],i6[12],i7[0],i8[0])->(o0[16x15]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[4]? arg[4][0] : 0;
  a1=arg[0]? arg[0][0] : 0;
  a2=(a0+a0);
  a2=(a1*a2);
  a2=(a0*a2);
  if (res[0]!=0) res[0][0]=a2;
  a2=0.;
  if (res[0]!=0) res[0][1]=a2;
  if (res[0]!=0) res[0][2]=a2;
  if (res[0]!=0) res[0][3]=a2;
  if (res[0]!=0) res[0][4]=a2;
  if (res[0]!=0) res[0][5]=a2;
  if (res[0]!=0) res[0][6]=a2;
  if (res[0]!=0) res[0][7]=a2;
  if (res[0]!=0) res[0][8]=a2;
  if (res[0]!=0) res[0][9]=a2;
  if (res[0]!=0) res[0][10]=a2;
  if (res[0]!=0) res[0][11]=a2;
  if (res[0]!=0) res[0][12]=a2;
  if (res[0]!=0) res[0][13]=a2;
  if (res[0]!=0) res[0][14]=a2;
  a3=arg[3]? arg[3][0] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][15]=a0;
  if (res[0]!=0) res[0][16]=a2;
  a0=arg[4]? arg[4][1] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][17]=a3;
  if (res[0]!=0) res[0][18]=a2;
  if (res[0]!=0) res[0][19]=a2;
  if (res[0]!=0) res[0][20]=a2;
  if (res[0]!=0) res[0][21]=a2;
  if (res[0]!=0) res[0][22]=a2;
  if (res[0]!=0) res[0][23]=a2;
  if (res[0]!=0) res[0][24]=a2;
  if (res[0]!=0) res[0][25]=a2;
  if (res[0]!=0) res[0][26]=a2;
  if (res[0]!=0) res[0][27]=a2;
  if (res[0]!=0) res[0][28]=a2;
  if (res[0]!=0) res[0][29]=a2;
  if (res[0]!=0) res[0][30]=a2;
  a3=arg[3]? arg[3][1] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a2;
  if (res[0]!=0) res[0][33]=a2;
  a0=arg[4]? arg[4][2] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][34]=a3;
  if (res[0]!=0) res[0][35]=a2;
  if (res[0]!=0) res[0][36]=a2;
  if (res[0]!=0) res[0][37]=a2;
  if (res[0]!=0) res[0][38]=a2;
  if (res[0]!=0) res[0][39]=a2;
  if (res[0]!=0) res[0][40]=a2;
  if (res[0]!=0) res[0][41]=a2;
  if (res[0]!=0) res[0][42]=a2;
  if (res[0]!=0) res[0][43]=a2;
  if (res[0]!=0) res[0][44]=a2;
  if (res[0]!=0) res[0][45]=a2;
  if (res[0]!=0) res[0][46]=a2;
  a3=arg[3]? arg[3][2] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][47]=a0;
  if (res[0]!=0) res[0][48]=a2;
  if (res[0]!=0) res[0][49]=a2;
  if (res[0]!=0) res[0][50]=a2;
  a0=arg[2]? arg[2][0] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][51]=a3;
  if (res[0]!=0) res[0][52]=a2;
  if (res[0]!=0) res[0][53]=a2;
  if (res[0]!=0) res[0][54]=a2;
  if (res[0]!=0) res[0][55]=a2;
  if (res[0]!=0) res[0][56]=a2;
  if (res[0]!=0) res[0][57]=a2;
  if (res[0]!=0) res[0][58]=a2;
  if (res[0]!=0) res[0][59]=a2;
  if (res[0]!=0) res[0][60]=a2;
  if (res[0]!=0) res[0][61]=a2;
  if (res[0]!=0) res[0][62]=a2;
  a3=arg[1]? arg[1][0] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][63]=a0;
  if (res[0]!=0) res[0][64]=a2;
  if (res[0]!=0) res[0][65]=a2;
  if (res[0]!=0) res[0][66]=a2;
  if (res[0]!=0) res[0][67]=a2;
  a0=arg[2]? arg[2][1] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][68]=a3;
  if (res[0]!=0) res[0][69]=a2;
  if (res[0]!=0) res[0][70]=a2;
  if (res[0]!=0) res[0][71]=a2;
  if (res[0]!=0) res[0][72]=a2;
  if (res[0]!=0) res[0][73]=a2;
  if (res[0]!=0) res[0][74]=a2;
  if (res[0]!=0) res[0][75]=a2;
  if (res[0]!=0) res[0][76]=a2;
  if (res[0]!=0) res[0][77]=a2;
  if (res[0]!=0) res[0][78]=a2;
  a3=arg[1]? arg[1][1] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][79]=a0;
  if (res[0]!=0) res[0][80]=a2;
  if (res[0]!=0) res[0][81]=a2;
  if (res[0]!=0) res[0][82]=a2;
  if (res[0]!=0) res[0][83]=a2;
  if (res[0]!=0) res[0][84]=a2;
  a0=arg[2]? arg[2][2] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][85]=a3;
  if (res[0]!=0) res[0][86]=a2;
  if (res[0]!=0) res[0][87]=a2;
  if (res[0]!=0) res[0][88]=a2;
  if (res[0]!=0) res[0][89]=a2;
  if (res[0]!=0) res[0][90]=a2;
  if (res[0]!=0) res[0][91]=a2;
  if (res[0]!=0) res[0][92]=a2;
  if (res[0]!=0) res[0][93]=a2;
  if (res[0]!=0) res[0][94]=a2;
  a3=arg[1]? arg[1][2] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][95]=a0;
  if (res[0]!=0) res[0][96]=a2;
  if (res[0]!=0) res[0][97]=a2;
  if (res[0]!=0) res[0][98]=a2;
  if (res[0]!=0) res[0][99]=a2;
  if (res[0]!=0) res[0][100]=a2;
  if (res[0]!=0) res[0][101]=a2;
  a0=arg[2]? arg[2][3] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][102]=a3;
  if (res[0]!=0) res[0][103]=a2;
  if (res[0]!=0) res[0][104]=a2;
  if (res[0]!=0) res[0][105]=a2;
  if (res[0]!=0) res[0][106]=a2;
  if (res[0]!=0) res[0][107]=a2;
  if (res[0]!=0) res[0][108]=a2;
  if (res[0]!=0) res[0][109]=a2;
  if (res[0]!=0) res[0][110]=a2;
  a3=arg[1]? arg[1][3] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][111]=a0;
  if (res[0]!=0) res[0][112]=a2;
  if (res[0]!=0) res[0][113]=a2;
  if (res[0]!=0) res[0][114]=a2;
  if (res[0]!=0) res[0][115]=a2;
  if (res[0]!=0) res[0][116]=a2;
  if (res[0]!=0) res[0][117]=a2;
  if (res[0]!=0) res[0][118]=a2;
  a0=arg[2]? arg[2][4] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][119]=a3;
  if (res[0]!=0) res[0][120]=a2;
  if (res[0]!=0) res[0][121]=a2;
  if (res[0]!=0) res[0][122]=a2;
  if (res[0]!=0) res[0][123]=a2;
  if (res[0]!=0) res[0][124]=a2;
  if (res[0]!=0) res[0][125]=a2;
  if (res[0]!=0) res[0][126]=a2;
  a3=arg[1]? arg[1][4] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][127]=a0;
  if (res[0]!=0) res[0][128]=a2;
  if (res[0]!=0) res[0][129]=a2;
  if (res[0]!=0) res[0][130]=a2;
  if (res[0]!=0) res[0][131]=a2;
  if (res[0]!=0) res[0][132]=a2;
  if (res[0]!=0) res[0][133]=a2;
  if (res[0]!=0) res[0][134]=a2;
  if (res[0]!=0) res[0][135]=a2;
  a0=arg[2]? arg[2][5] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][136]=a3;
  if (res[0]!=0) res[0][137]=a2;
  if (res[0]!=0) res[0][138]=a2;
  if (res[0]!=0) res[0][139]=a2;
  if (res[0]!=0) res[0][140]=a2;
  if (res[0]!=0) res[0][141]=a2;
  if (res[0]!=0) res[0][142]=a2;
  a3=arg[1]? arg[1][5] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][143]=a0;
  if (res[0]!=0) res[0][144]=a2;
  if (res[0]!=0) res[0][145]=a2;
  if (res[0]!=0) res[0][146]=a2;
  if (res[0]!=0) res[0][147]=a2;
  if (res[0]!=0) res[0][148]=a2;
  if (res[0]!=0) res[0][149]=a2;
  if (res[0]!=0) res[0][150]=a2;
  if (res[0]!=0) res[0][151]=a2;
  if (res[0]!=0) res[0][152]=a2;
  a0=arg[2]? arg[2][6] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][153]=a3;
  if (res[0]!=0) res[0][154]=a2;
  if (res[0]!=0) res[0][155]=a2;
  if (res[0]!=0) res[0][156]=a2;
  if (res[0]!=0) res[0][157]=a2;
  if (res[0]!=0) res[0][158]=a2;
  a3=arg[1]? arg[1][6] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][159]=a0;
  if (res[0]!=0) res[0][160]=a2;
  if (res[0]!=0) res[0][161]=a2;
  if (res[0]!=0) res[0][162]=a2;
  if (res[0]!=0) res[0][163]=a2;
  if (res[0]!=0) res[0][164]=a2;
  if (res[0]!=0) res[0][165]=a2;
  if (res[0]!=0) res[0][166]=a2;
  if (res[0]!=0) res[0][167]=a2;
  if (res[0]!=0) res[0][168]=a2;
  if (res[0]!=0) res[0][169]=a2;
  a0=arg[2]? arg[2][7] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][170]=a3;
  if (res[0]!=0) res[0][171]=a2;
  if (res[0]!=0) res[0][172]=a2;
  if (res[0]!=0) res[0][173]=a2;
  if (res[0]!=0) res[0][174]=a2;
  a3=arg[1]? arg[1][7] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][175]=a0;
  if (res[0]!=0) res[0][176]=a2;
  if (res[0]!=0) res[0][177]=a2;
  if (res[0]!=0) res[0][178]=a2;
  if (res[0]!=0) res[0][179]=a2;
  if (res[0]!=0) res[0][180]=a2;
  if (res[0]!=0) res[0][181]=a2;
  if (res[0]!=0) res[0][182]=a2;
  if (res[0]!=0) res[0][183]=a2;
  if (res[0]!=0) res[0][184]=a2;
  if (res[0]!=0) res[0][185]=a2;
  if (res[0]!=0) res[0][186]=a2;
  a0=arg[2]? arg[2][8] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][187]=a3;
  if (res[0]!=0) res[0][188]=a2;
  if (res[0]!=0) res[0][189]=a2;
  if (res[0]!=0) res[0][190]=a2;
  a3=arg[1]? arg[1][8] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][191]=a0;
  if (res[0]!=0) res[0][192]=a2;
  if (res[0]!=0) res[0][193]=a2;
  if (res[0]!=0) res[0][194]=a2;
  if (res[0]!=0) res[0][195]=a2;
  if (res[0]!=0) res[0][196]=a2;
  if (res[0]!=0) res[0][197]=a2;
  if (res[0]!=0) res[0][198]=a2;
  if (res[0]!=0) res[0][199]=a2;
  if (res[0]!=0) res[0][200]=a2;
  if (res[0]!=0) res[0][201]=a2;
  if (res[0]!=0) res[0][202]=a2;
  if (res[0]!=0) res[0][203]=a2;
  a0=arg[2]? arg[2][9] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][204]=a3;
  if (res[0]!=0) res[0][205]=a2;
  if (res[0]!=0) res[0][206]=a2;
  a3=arg[1]? arg[1][9] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][207]=a0;
  if (res[0]!=0) res[0][208]=a2;
  if (res[0]!=0) res[0][209]=a2;
  if (res[0]!=0) res[0][210]=a2;
  if (res[0]!=0) res[0][211]=a2;
  if (res[0]!=0) res[0][212]=a2;
  if (res[0]!=0) res[0][213]=a2;
  if (res[0]!=0) res[0][214]=a2;
  if (res[0]!=0) res[0][215]=a2;
  if (res[0]!=0) res[0][216]=a2;
  if (res[0]!=0) res[0][217]=a2;
  if (res[0]!=0) res[0][218]=a2;
  if (res[0]!=0) res[0][219]=a2;
  if (res[0]!=0) res[0][220]=a2;
  a0=arg[2]? arg[2][10] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][221]=a3;
  if (res[0]!=0) res[0][222]=a2;
  a3=arg[1]? arg[1][10] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][223]=a0;
  if (res[0]!=0) res[0][224]=a2;
  if (res[0]!=0) res[0][225]=a2;
  if (res[0]!=0) res[0][226]=a2;
  if (res[0]!=0) res[0][227]=a2;
  if (res[0]!=0) res[0][228]=a2;
  if (res[0]!=0) res[0][229]=a2;
  if (res[0]!=0) res[0][230]=a2;
  if (res[0]!=0) res[0][231]=a2;
  if (res[0]!=0) res[0][232]=a2;
  if (res[0]!=0) res[0][233]=a2;
  if (res[0]!=0) res[0][234]=a2;
  if (res[0]!=0) res[0][235]=a2;
  if (res[0]!=0) res[0][236]=a2;
  if (res[0]!=0) res[0][237]=a2;
  a2=arg[2]? arg[2][11] : 0;
  a0=(a2+a2);
  a0=(a1*a0);
  a0=(a2*a0);
  if (res[0]!=0) res[0][238]=a0;
  a0=arg[1]? arg[1][11] : 0;
  a0=(a2*a0);
  a0=(a0+a0);
  a0=(a0*a1);
  a2=(a2*a0);
  if (res[0]!=0) res[0][239]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int RSQrqt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int RSQrqt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void RSQrqt_incref(void) {
}

CASADI_SYMBOL_EXPORT void RSQrqt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int RSQrqt_n_in(void) { return 9;}

CASADI_SYMBOL_EXPORT casadi_int RSQrqt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real RSQrqt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s4;
    case 8: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int RSQrqt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* rqk:(i0,i1[12],i2[12],i3[3],i4[3],i5[12],i6[0])->(o0[15]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=arg[4]? arg[4][0] : 0;
  a1=arg[3]? arg[3][0] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a2=arg[0]? arg[0][0] : 0;
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[4]? arg[4][1] : 0;
  a1=arg[3]? arg[3][1] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[4]? arg[4][2] : 0;
  a1=arg[3]? arg[3][2] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[2]? arg[2][0] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[2]? arg[2][1] : 0;
  a1=arg[1]? arg[1][1] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[2]? arg[2][2] : 0;
  a1=arg[1]? arg[1][2] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[2]? arg[2][3] : 0;
  a1=arg[1]? arg[1][3] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[2]? arg[2][4] : 0;
  a1=arg[1]? arg[1][4] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[2]? arg[2][5] : 0;
  a1=arg[1]? arg[1][5] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[2]? arg[2][6] : 0;
  a1=arg[1]? arg[1][6] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[2]? arg[2][7] : 0;
  a1=arg[1]? arg[1][7] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[2]? arg[2][8] : 0;
  a1=arg[1]? arg[1][8] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[2]? arg[2][9] : 0;
  a1=arg[1]? arg[1][9] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][12]=a0;
  a0=arg[2]? arg[2][10] : 0;
  a1=arg[1]? arg[1][10] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][13]=a0;
  a0=arg[2]? arg[2][11] : 0;
  a1=arg[1]? arg[1][11] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][14]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rqk(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rqk_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rqk_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqk_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rqk_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqk_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rqk_incref(void) {
}

CASADI_SYMBOL_EXPORT void rqk_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rqk_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int rqk_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rqk_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqk_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqk_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqk_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s0;
    case 6: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqk_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rqk_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* Lk:(i0,i1[12],i2[12],i3[3],i4[3])->(o0) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[2]? arg[2][0] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1*a2);
  a1=casadi_sq(a1);
  a2=arg[2]? arg[2][1] : 0;
  a3=arg[1]? arg[1][1] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][2] : 0;
  a3=arg[1]? arg[1][2] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][3] : 0;
  a3=arg[1]? arg[1][3] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][4] : 0;
  a3=arg[1]? arg[1][4] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][5] : 0;
  a3=arg[1]? arg[1][5] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][6] : 0;
  a3=arg[1]? arg[1][6] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][7] : 0;
  a3=arg[1]? arg[1][7] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][8] : 0;
  a3=arg[1]? arg[1][8] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][9] : 0;
  a3=arg[1]? arg[1][9] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][10] : 0;
  a3=arg[1]? arg[1][10] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][11] : 0;
  a3=arg[1]? arg[1][11] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[4]? arg[4][0] : 0;
  a3=arg[3]? arg[3][0] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a3=arg[4]? arg[4][1] : 0;
  a4=arg[3]? arg[3][1] : 0;
  a3=(a3*a4);
  a3=casadi_sq(a3);
  a2=(a2+a3);
  a3=arg[4]? arg[4][2] : 0;
  a4=arg[3]? arg[3][2] : 0;
  a3=(a3*a4);
  a3=casadi_sq(a3);
  a2=(a2+a3);
  a1=(a1+a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Lk(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Lk_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Lk_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Lk_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Lk_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Lk_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Lk_incref(void) {
}

CASADI_SYMBOL_EXPORT void Lk_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Lk_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Lk_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Lk_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Lk_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Lk_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Lk_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Lk_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Lk_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* RSQrqtF:(i0,i1[12],i2[12],i3[3],i4[3],i5[12],i6[12],i7[0],i8[0])->(o0[13x12]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[2]? arg[2][0] : 0;
  a1=arg[0]? arg[0][0] : 0;
  a2=(a0+a0);
  a2=(a1*a2);
  a2=(a0*a2);
  if (res[0]!=0) res[0][0]=a2;
  a2=0.;
  if (res[0]!=0) res[0][1]=a2;
  if (res[0]!=0) res[0][2]=a2;
  if (res[0]!=0) res[0][3]=a2;
  if (res[0]!=0) res[0][4]=a2;
  if (res[0]!=0) res[0][5]=a2;
  if (res[0]!=0) res[0][6]=a2;
  if (res[0]!=0) res[0][7]=a2;
  if (res[0]!=0) res[0][8]=a2;
  if (res[0]!=0) res[0][9]=a2;
  if (res[0]!=0) res[0][10]=a2;
  if (res[0]!=0) res[0][11]=a2;
  a3=arg[1]? arg[1][0] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a2;
  a0=arg[2]? arg[2][1] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][14]=a3;
  if (res[0]!=0) res[0][15]=a2;
  if (res[0]!=0) res[0][16]=a2;
  if (res[0]!=0) res[0][17]=a2;
  if (res[0]!=0) res[0][18]=a2;
  if (res[0]!=0) res[0][19]=a2;
  if (res[0]!=0) res[0][20]=a2;
  if (res[0]!=0) res[0][21]=a2;
  if (res[0]!=0) res[0][22]=a2;
  if (res[0]!=0) res[0][23]=a2;
  if (res[0]!=0) res[0][24]=a2;
  a3=arg[1]? arg[1][1] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a2;
  if (res[0]!=0) res[0][27]=a2;
  a0=arg[2]? arg[2][2] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][28]=a3;
  if (res[0]!=0) res[0][29]=a2;
  if (res[0]!=0) res[0][30]=a2;
  if (res[0]!=0) res[0][31]=a2;
  if (res[0]!=0) res[0][32]=a2;
  if (res[0]!=0) res[0][33]=a2;
  if (res[0]!=0) res[0][34]=a2;
  if (res[0]!=0) res[0][35]=a2;
  if (res[0]!=0) res[0][36]=a2;
  if (res[0]!=0) res[0][37]=a2;
  a3=arg[1]? arg[1][2] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][38]=a0;
  if (res[0]!=0) res[0][39]=a2;
  if (res[0]!=0) res[0][40]=a2;
  if (res[0]!=0) res[0][41]=a2;
  a0=arg[2]? arg[2][3] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][42]=a3;
  if (res[0]!=0) res[0][43]=a2;
  if (res[0]!=0) res[0][44]=a2;
  if (res[0]!=0) res[0][45]=a2;
  if (res[0]!=0) res[0][46]=a2;
  if (res[0]!=0) res[0][47]=a2;
  if (res[0]!=0) res[0][48]=a2;
  if (res[0]!=0) res[0][49]=a2;
  if (res[0]!=0) res[0][50]=a2;
  a3=arg[1]? arg[1][3] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][51]=a0;
  if (res[0]!=0) res[0][52]=a2;
  if (res[0]!=0) res[0][53]=a2;
  if (res[0]!=0) res[0][54]=a2;
  if (res[0]!=0) res[0][55]=a2;
  a0=arg[2]? arg[2][4] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][56]=a3;
  if (res[0]!=0) res[0][57]=a2;
  if (res[0]!=0) res[0][58]=a2;
  if (res[0]!=0) res[0][59]=a2;
  if (res[0]!=0) res[0][60]=a2;
  if (res[0]!=0) res[0][61]=a2;
  if (res[0]!=0) res[0][62]=a2;
  if (res[0]!=0) res[0][63]=a2;
  a3=arg[1]? arg[1][4] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][64]=a0;
  if (res[0]!=0) res[0][65]=a2;
  if (res[0]!=0) res[0][66]=a2;
  if (res[0]!=0) res[0][67]=a2;
  if (res[0]!=0) res[0][68]=a2;
  if (res[0]!=0) res[0][69]=a2;
  a0=arg[2]? arg[2][5] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][70]=a3;
  if (res[0]!=0) res[0][71]=a2;
  if (res[0]!=0) res[0][72]=a2;
  if (res[0]!=0) res[0][73]=a2;
  if (res[0]!=0) res[0][74]=a2;
  if (res[0]!=0) res[0][75]=a2;
  if (res[0]!=0) res[0][76]=a2;
  a3=arg[1]? arg[1][5] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][77]=a0;
  if (res[0]!=0) res[0][78]=a2;
  if (res[0]!=0) res[0][79]=a2;
  if (res[0]!=0) res[0][80]=a2;
  if (res[0]!=0) res[0][81]=a2;
  if (res[0]!=0) res[0][82]=a2;
  if (res[0]!=0) res[0][83]=a2;
  a0=arg[2]? arg[2][6] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][84]=a3;
  if (res[0]!=0) res[0][85]=a2;
  if (res[0]!=0) res[0][86]=a2;
  if (res[0]!=0) res[0][87]=a2;
  if (res[0]!=0) res[0][88]=a2;
  if (res[0]!=0) res[0][89]=a2;
  a3=arg[1]? arg[1][6] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][90]=a0;
  if (res[0]!=0) res[0][91]=a2;
  if (res[0]!=0) res[0][92]=a2;
  if (res[0]!=0) res[0][93]=a2;
  if (res[0]!=0) res[0][94]=a2;
  if (res[0]!=0) res[0][95]=a2;
  if (res[0]!=0) res[0][96]=a2;
  if (res[0]!=0) res[0][97]=a2;
  a0=arg[2]? arg[2][7] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][98]=a3;
  if (res[0]!=0) res[0][99]=a2;
  if (res[0]!=0) res[0][100]=a2;
  if (res[0]!=0) res[0][101]=a2;
  if (res[0]!=0) res[0][102]=a2;
  a3=arg[1]? arg[1][7] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][103]=a0;
  if (res[0]!=0) res[0][104]=a2;
  if (res[0]!=0) res[0][105]=a2;
  if (res[0]!=0) res[0][106]=a2;
  if (res[0]!=0) res[0][107]=a2;
  if (res[0]!=0) res[0][108]=a2;
  if (res[0]!=0) res[0][109]=a2;
  if (res[0]!=0) res[0][110]=a2;
  if (res[0]!=0) res[0][111]=a2;
  a0=arg[2]? arg[2][8] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][112]=a3;
  if (res[0]!=0) res[0][113]=a2;
  if (res[0]!=0) res[0][114]=a2;
  if (res[0]!=0) res[0][115]=a2;
  a3=arg[1]? arg[1][8] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][116]=a0;
  if (res[0]!=0) res[0][117]=a2;
  if (res[0]!=0) res[0][118]=a2;
  if (res[0]!=0) res[0][119]=a2;
  if (res[0]!=0) res[0][120]=a2;
  if (res[0]!=0) res[0][121]=a2;
  if (res[0]!=0) res[0][122]=a2;
  if (res[0]!=0) res[0][123]=a2;
  if (res[0]!=0) res[0][124]=a2;
  if (res[0]!=0) res[0][125]=a2;
  a0=arg[2]? arg[2][9] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][126]=a3;
  if (res[0]!=0) res[0][127]=a2;
  if (res[0]!=0) res[0][128]=a2;
  a3=arg[1]? arg[1][9] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][129]=a0;
  if (res[0]!=0) res[0][130]=a2;
  if (res[0]!=0) res[0][131]=a2;
  if (res[0]!=0) res[0][132]=a2;
  if (res[0]!=0) res[0][133]=a2;
  if (res[0]!=0) res[0][134]=a2;
  if (res[0]!=0) res[0][135]=a2;
  if (res[0]!=0) res[0][136]=a2;
  if (res[0]!=0) res[0][137]=a2;
  if (res[0]!=0) res[0][138]=a2;
  if (res[0]!=0) res[0][139]=a2;
  a0=arg[2]? arg[2][10] : 0;
  a3=(a0+a0);
  a3=(a1*a3);
  a3=(a0*a3);
  if (res[0]!=0) res[0][140]=a3;
  if (res[0]!=0) res[0][141]=a2;
  a3=arg[1]? arg[1][10] : 0;
  a3=(a0*a3);
  a3=(a3+a3);
  a3=(a3*a1);
  a0=(a0*a3);
  if (res[0]!=0) res[0][142]=a0;
  if (res[0]!=0) res[0][143]=a2;
  if (res[0]!=0) res[0][144]=a2;
  if (res[0]!=0) res[0][145]=a2;
  if (res[0]!=0) res[0][146]=a2;
  if (res[0]!=0) res[0][147]=a2;
  if (res[0]!=0) res[0][148]=a2;
  if (res[0]!=0) res[0][149]=a2;
  if (res[0]!=0) res[0][150]=a2;
  if (res[0]!=0) res[0][151]=a2;
  if (res[0]!=0) res[0][152]=a2;
  if (res[0]!=0) res[0][153]=a2;
  a2=arg[2]? arg[2][11] : 0;
  a0=(a2+a2);
  a0=(a1*a0);
  a0=(a2*a0);
  if (res[0]!=0) res[0][154]=a0;
  a0=arg[1]? arg[1][11] : 0;
  a0=(a2*a0);
  a0=(a0+a0);
  a0=(a0*a1);
  a2=(a2*a0);
  if (res[0]!=0) res[0][155]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int RSQrqtF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int RSQrqtF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void RSQrqtF_incref(void) {
}

CASADI_SYMBOL_EXPORT void RSQrqtF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtF_n_in(void) { return 9;}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real RSQrqtF_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtF_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtF_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s4;
    case 8: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int RSQrqtF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* rqF:(i0,i1[12],i2[12],i3[3],i4[3],i5[12],i6[0])->(o0[12]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=arg[2]? arg[2][0] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a2=arg[0]? arg[0][0] : 0;
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[2]? arg[2][1] : 0;
  a1=arg[1]? arg[1][1] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[2]? arg[2][2] : 0;
  a1=arg[1]? arg[1][2] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[2]? arg[2][3] : 0;
  a1=arg[1]? arg[1][3] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[2]? arg[2][4] : 0;
  a1=arg[1]? arg[1][4] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[2]? arg[2][5] : 0;
  a1=arg[1]? arg[1][5] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[2]? arg[2][6] : 0;
  a1=arg[1]? arg[1][6] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[2]? arg[2][7] : 0;
  a1=arg[1]? arg[1][7] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[2]? arg[2][8] : 0;
  a1=arg[1]? arg[1][8] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[2]? arg[2][9] : 0;
  a1=arg[1]? arg[1][9] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[2]? arg[2][10] : 0;
  a1=arg[1]? arg[1][10] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[2]? arg[2][11] : 0;
  a1=arg[1]? arg[1][11] : 0;
  a1=(a0*a1);
  a1=(a1+a1);
  a1=(a1*a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][11]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rqF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rqF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rqF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rqF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rqF_incref(void) {
}

CASADI_SYMBOL_EXPORT void rqF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rqF_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int rqF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rqF_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqF_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqF_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s0;
    case 6: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rqF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* LF:(i0,i1[12],i2[12],i3[3],i4[3])->(o0) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[2]? arg[2][0] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1*a2);
  a1=casadi_sq(a1);
  a2=arg[2]? arg[2][1] : 0;
  a3=arg[1]? arg[1][1] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][2] : 0;
  a3=arg[1]? arg[1][2] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][3] : 0;
  a3=arg[1]? arg[1][3] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][4] : 0;
  a3=arg[1]? arg[1][4] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][5] : 0;
  a3=arg[1]? arg[1][5] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][6] : 0;
  a3=arg[1]? arg[1][6] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][7] : 0;
  a3=arg[1]? arg[1][7] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][8] : 0;
  a3=arg[1]? arg[1][8] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][9] : 0;
  a3=arg[1]? arg[1][9] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][10] : 0;
  a3=arg[1]? arg[1][10] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a2=arg[2]? arg[2][11] : 0;
  a3=arg[1]? arg[1][11] : 0;
  a2=(a2*a3);
  a2=casadi_sq(a2);
  a1=(a1+a2);
  a0=(a0*a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int LF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f9(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int LF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int LF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void LF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int LF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void LF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void LF_incref(void) {
}

CASADI_SYMBOL_EXPORT void LF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int LF_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int LF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real LF_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* LF_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* LF_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* LF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* LF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int LF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* GgtI:(i0[12],i1[12],i2[3],i3[3],i4[0])->(o0[16x0]) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GgtI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f10(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GgtI_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GgtI_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgtI_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GgtI_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgtI_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GgtI_incref(void) {
}

CASADI_SYMBOL_EXPORT void GgtI_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GgtI_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int GgtI_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real GgtI_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgtI_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgtI_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgtI_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgtI_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GgtI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* gI:(i0[12],i1[12],i2[3],i3[3],i4[0])->(o0[0]) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f11(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int gI_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gI_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gI_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int gI_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gI_release(int mem) {
}

CASADI_SYMBOL_EXPORT void gI_incref(void) {
}

CASADI_SYMBOL_EXPORT void gI_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int gI_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int gI_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real gI_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gI_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gI_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gI_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gI_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* GgtF:(i0[12],i1[12],i2[3],i3[3],i4[0])->(o0[13x0]) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GgtF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f12(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GgtF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GgtF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgtF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GgtF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgtF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GgtF_incref(void) {
}

CASADI_SYMBOL_EXPORT void GgtF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GgtF_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int GgtF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real GgtF_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgtF_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgtF_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgtF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgtF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GgtF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* gF:(i0[12],i1[12],i2[3],i3[3],i4[0])->(o0[0]) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f13(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int gF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int gF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void gF_incref(void) {
}

CASADI_SYMBOL_EXPORT void gF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int gF_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int gF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real gF_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gF_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gF_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
