/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f15 CASADI_PREFIX(f15)
#define casadi_f16 CASADI_PREFIX(f16)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[120] = {12, 9, 0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s6[146] = {12, 11, 0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s7[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s8[102] = {10, 9, 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s9[55] = {12, 4, 0, 12, 24, 36, 48, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s10[47] = {10, 4, 0, 10, 20, 30, 40, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s11[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* BAbt:(i0[9],i1[2],i2[9],i3[0],i4[0])->(o0[12x9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a1=1.;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  a2=1.0000000000000001e-01;
  if (res[0]!=0) res[0][8]=a2;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  a3=arg[2]? arg[2][0] : 0;
  a4=arg[2]? arg[2][6] : 0;
  a5=(a2*a4);
  a3=(a3+a5);
  a5=arg[0]? arg[0][0] : 0;
  a3=(a3-a5);
  if (res[0]!=0) res[0][11]=a3;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a0;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a2;
  if (res[0]!=0) res[0][22]=a0;
  a3=arg[2]? arg[2][1] : 0;
  a5=arg[2]? arg[2][7] : 0;
  a6=(a2*a5);
  a3=(a3+a6);
  a6=arg[0]? arg[0][1] : 0;
  a3=(a3-a6);
  if (res[0]!=0) res[0][23]=a3;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a0;
  a3=arg[2]? arg[2][8] : 0;
  a6=(a2*a3);
  a7=cos(a6);
  if (res[0]!=0) res[0][28]=a7;
  a8=(a2*a3);
  a9=sin(a8);
  a10=(-a9);
  if (res[0]!=0) res[0][29]=a10;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a0;
  if (res[0]!=0) res[0][33]=a0;
  a10=arg[2]? arg[2][2] : 0;
  a6=sin(a6);
  a6=(a2*a6);
  a11=(a10*a6);
  a12=arg[2]? arg[2][3] : 0;
  a8=cos(a8);
  a8=(a2*a8);
  a13=(a12*a8);
  a11=(a11+a13);
  a11=(-a11);
  if (res[0]!=0) res[0][34]=a11;
  a11=(a7*a10);
  a13=(a9*a12);
  a11=(a11-a13);
  a13=arg[0]? arg[0][2] : 0;
  a11=(a11-a13);
  if (res[0]!=0) res[0][35]=a11;
  if (res[0]!=0) res[0][36]=a0;
  if (res[0]!=0) res[0][37]=a0;
  if (res[0]!=0) res[0][38]=a0;
  if (res[0]!=0) res[0][39]=a0;
  a11=(a2*a3);
  a13=sin(a11);
  if (res[0]!=0) res[0][40]=a13;
  a14=(a2*a3);
  a15=cos(a14);
  if (res[0]!=0) res[0][41]=a15;
  if (res[0]!=0) res[0][42]=a0;
  if (res[0]!=0) res[0][43]=a0;
  if (res[0]!=0) res[0][44]=a0;
  if (res[0]!=0) res[0][45]=a0;
  a11=cos(a11);
  a11=(a2*a11);
  a16=(a10*a11);
  a14=sin(a14);
  a14=(a2*a14);
  a17=(a12*a14);
  a16=(a16-a17);
  if (res[0]!=0) res[0][46]=a16;
  a10=(a13*a10);
  a12=(a15*a12);
  a10=(a10+a12);
  a12=arg[0]? arg[0][3] : 0;
  a10=(a10-a12);
  if (res[0]!=0) res[0][47]=a10;
  if (res[0]!=0) res[0][48]=a0;
  if (res[0]!=0) res[0][49]=a0;
  if (res[0]!=0) res[0][50]=a0;
  if (res[0]!=0) res[0][51]=a0;
  if (res[0]!=0) res[0][52]=a0;
  if (res[0]!=0) res[0][53]=a0;
  if (res[0]!=0) res[0][54]=a7;
  a10=(-a9);
  if (res[0]!=0) res[0][55]=a10;
  if (res[0]!=0) res[0][56]=a0;
  if (res[0]!=0) res[0][57]=a0;
  a10=arg[2]? arg[2][4] : 0;
  a6=(a10*a6);
  a12=arg[2]? arg[2][5] : 0;
  a8=(a12*a8);
  a6=(a6+a8);
  a6=(-a6);
  if (res[0]!=0) res[0][58]=a6;
  a7=(a7*a10);
  a9=(a9*a12);
  a7=(a7-a9);
  a9=arg[0]? arg[0][4] : 0;
  a7=(a7-a9);
  if (res[0]!=0) res[0][59]=a7;
  if (res[0]!=0) res[0][60]=a0;
  if (res[0]!=0) res[0][61]=a0;
  if (res[0]!=0) res[0][62]=a0;
  if (res[0]!=0) res[0][63]=a0;
  if (res[0]!=0) res[0][64]=a0;
  if (res[0]!=0) res[0][65]=a0;
  if (res[0]!=0) res[0][66]=a13;
  if (res[0]!=0) res[0][67]=a15;
  if (res[0]!=0) res[0][68]=a0;
  if (res[0]!=0) res[0][69]=a0;
  a11=(a10*a11);
  a14=(a12*a14);
  a11=(a11-a14);
  if (res[0]!=0) res[0][70]=a11;
  a13=(a13*a10);
  a15=(a15*a12);
  a13=(a13+a15);
  a15=arg[0]? arg[0][5] : 0;
  a13=(a13-a15);
  if (res[0]!=0) res[0][71]=a13;
  a13=(a2*a10);
  if (res[0]!=0) res[0][72]=a13;
  if (res[0]!=0) res[0][73]=a0;
  if (res[0]!=0) res[0][74]=a0;
  if (res[0]!=0) res[0][75]=a0;
  if (res[0]!=0) res[0][76]=a0;
  if (res[0]!=0) res[0][77]=a0;
  a13=arg[1]? arg[1][0] : 0;
  a15=(a2*a13);
  if (res[0]!=0) res[0][78]=a15;
  if (res[0]!=0) res[0][79]=a0;
  if (res[0]!=0) res[0][80]=a1;
  if (res[0]!=0) res[0][81]=a0;
  if (res[0]!=0) res[0][82]=a0;
  a10=(a10*a13);
  a10=(a2*a10);
  a4=(a4+a10);
  a10=arg[0]? arg[0][6] : 0;
  a4=(a4-a10);
  if (res[0]!=0) res[0][83]=a4;
  a4=(a2*a12);
  if (res[0]!=0) res[0][84]=a4;
  if (res[0]!=0) res[0][85]=a0;
  if (res[0]!=0) res[0][86]=a0;
  if (res[0]!=0) res[0][87]=a0;
  if (res[0]!=0) res[0][88]=a0;
  if (res[0]!=0) res[0][89]=a0;
  if (res[0]!=0) res[0][90]=a0;
  a4=(a2*a13);
  if (res[0]!=0) res[0][91]=a4;
  if (res[0]!=0) res[0][92]=a0;
  if (res[0]!=0) res[0][93]=a1;
  if (res[0]!=0) res[0][94]=a0;
  a12=(a12*a13);
  a12=(a2*a12);
  a5=(a5+a12);
  a12=arg[0]? arg[0][7] : 0;
  a5=(a5-a12);
  if (res[0]!=0) res[0][95]=a5;
  if (res[0]!=0) res[0][96]=a0;
  if (res[0]!=0) res[0][97]=a2;
  if (res[0]!=0) res[0][98]=a0;
  if (res[0]!=0) res[0][99]=a0;
  if (res[0]!=0) res[0][100]=a0;
  if (res[0]!=0) res[0][101]=a0;
  if (res[0]!=0) res[0][102]=a0;
  if (res[0]!=0) res[0][103]=a0;
  if (res[0]!=0) res[0][104]=a0;
  if (res[0]!=0) res[0][105]=a0;
  if (res[0]!=0) res[0][106]=a1;
  a1=arg[1]? arg[1][1] : 0;
  a2=(a2*a1);
  a3=(a3+a2);
  a2=arg[0]? arg[0][8] : 0;
  a3=(a3-a2);
  if (res[0]!=0) res[0][107]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int BAbt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int BAbt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int BAbt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BAbt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int BAbt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BAbt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void BAbt_incref(void) {
}

CASADI_SYMBOL_EXPORT void BAbt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int BAbt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int BAbt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real BAbt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BAbt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BAbt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BAbt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BAbt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int BAbt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* bk:(i0[9],i1[2],i2[9],i3[0],i4[0])->(o0[9]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[2]? arg[2][0] : 0;
  a1=1.0000000000000001e-01;
  a2=arg[2]? arg[2][6] : 0;
  a3=(a1*a2);
  a0=(a0+a3);
  a3=arg[0]? arg[0][0] : 0;
  a0=(a0-a3);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[2]? arg[2][1] : 0;
  a3=arg[2]? arg[2][7] : 0;
  a4=(a1*a3);
  a0=(a0+a4);
  a4=arg[0]? arg[0][1] : 0;
  a0=(a0-a4);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[2]? arg[2][8] : 0;
  a4=(a1*a0);
  a4=cos(a4);
  a5=arg[2]? arg[2][2] : 0;
  a6=(a4*a5);
  a7=(a1*a0);
  a7=sin(a7);
  a8=arg[2]? arg[2][3] : 0;
  a9=(a7*a8);
  a6=(a6-a9);
  a9=arg[0]? arg[0][2] : 0;
  a6=(a6-a9);
  if (res[0]!=0) res[0][2]=a6;
  a6=(a1*a0);
  a6=sin(a6);
  a5=(a6*a5);
  a9=(a1*a0);
  a9=cos(a9);
  a8=(a9*a8);
  a5=(a5+a8);
  a8=arg[0]? arg[0][3] : 0;
  a5=(a5-a8);
  if (res[0]!=0) res[0][3]=a5;
  a5=arg[2]? arg[2][4] : 0;
  a4=(a4*a5);
  a8=arg[2]? arg[2][5] : 0;
  a7=(a7*a8);
  a4=(a4-a7);
  a7=arg[0]? arg[0][4] : 0;
  a4=(a4-a7);
  if (res[0]!=0) res[0][4]=a4;
  a6=(a6*a5);
  a9=(a9*a8);
  a6=(a6+a9);
  a9=arg[0]? arg[0][5] : 0;
  a6=(a6-a9);
  if (res[0]!=0) res[0][5]=a6;
  a6=arg[1]? arg[1][0] : 0;
  a5=(a5*a6);
  a5=(a1*a5);
  a2=(a2+a5);
  a5=arg[0]? arg[0][6] : 0;
  a2=(a2-a5);
  if (res[0]!=0) res[0][6]=a2;
  a8=(a8*a6);
  a8=(a1*a8);
  a3=(a3+a8);
  a8=arg[0]? arg[0][7] : 0;
  a3=(a3-a8);
  if (res[0]!=0) res[0][7]=a3;
  a3=arg[1]? arg[1][1] : 0;
  a1=(a1*a3);
  a0=(a0+a1);
  a1=arg[0]? arg[0][8] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bk(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bk_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bk_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bk_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bk_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bk_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bk_incref(void) {
}

CASADI_SYMBOL_EXPORT void bk_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bk_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int bk_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bk_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bk_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bk_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bk_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bk_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bk_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* RSQrqtI:(i0,i1[2],i2[9],i3[9],i4[4],i5,i6[0],i7[0])->(o0[12x11]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a3, a4, a5, a6, a7, a8, a9;
  a0=2.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  a2=1.0000000000000001e-01;
  a3=arg[3]? arg[3][6] : 0;
  a3=(a2*a3);
  if (res[0]!=0) res[0][6]=a3;
  a4=arg[3]? arg[3][7] : 0;
  a4=(a2*a4);
  if (res[0]!=0) res[0][7]=a4;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a1;
  a5=arg[1]? arg[1][0] : 0;
  a5=(a5+a5);
  if (res[0]!=0) res[0][11]=a5;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a1;
  if (res[0]!=0) res[0][19]=a1;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a1;
  if (res[0]!=0) res[0][22]=a1;
  a5=arg[1]? arg[1][1] : 0;
  a5=(a5+a5);
  if (res[0]!=0) res[0][23]=a5;
  if (res[0]!=0) res[0][24]=a1;
  if (res[0]!=0) res[0][25]=a1;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a1;
  if (res[0]!=0) res[0][28]=a1;
  if (res[0]!=0) res[0][29]=a1;
  if (res[0]!=0) res[0][30]=a1;
  if (res[0]!=0) res[0][31]=a1;
  if (res[0]!=0) res[0][32]=a1;
  if (res[0]!=0) res[0][33]=a1;
  if (res[0]!=0) res[0][34]=a1;
  a5=1.;
  a6=arg[2]? arg[2][0] : 0;
  a6=(a6+a6);
  a6=(a5+a6);
  if (res[0]!=0) res[0][35]=a6;
  if (res[0]!=0) res[0][36]=a1;
  if (res[0]!=0) res[0][37]=a1;
  if (res[0]!=0) res[0][38]=a1;
  if (res[0]!=0) res[0][39]=a0;
  if (res[0]!=0) res[0][40]=a1;
  if (res[0]!=0) res[0][41]=a1;
  if (res[0]!=0) res[0][42]=a1;
  if (res[0]!=0) res[0][43]=a1;
  if (res[0]!=0) res[0][44]=a1;
  if (res[0]!=0) res[0][45]=a1;
  if (res[0]!=0) res[0][46]=a1;
  a6=arg[2]? arg[2][1] : 0;
  a6=(a6+a6);
  a6=(a5+a6);
  if (res[0]!=0) res[0][47]=a6;
  if (res[0]!=0) res[0][48]=a1;
  if (res[0]!=0) res[0][49]=a1;
  if (res[0]!=0) res[0][50]=a1;
  if (res[0]!=0) res[0][51]=a1;
  if (res[0]!=0) res[0][52]=a0;
  if (res[0]!=0) res[0][53]=a1;
  if (res[0]!=0) res[0][54]=a1;
  if (res[0]!=0) res[0][55]=a1;
  if (res[0]!=0) res[0][56]=a1;
  if (res[0]!=0) res[0][57]=a1;
  a6=arg[3]? arg[3][3] : 0;
  a7=arg[2]? arg[2][8] : 0;
  a8=(a2*a7);
  a9=cos(a8);
  a9=(a2*a9);
  a10=(a6*a9);
  a11=arg[3]? arg[3][2] : 0;
  a12=(a2*a7);
  a13=sin(a12);
  a13=(a2*a13);
  a14=(a11*a13);
  a10=(a10-a14);
  if (res[0]!=0) res[0][58]=a10;
  a14=arg[2]? arg[2][2] : 0;
  a15=(a14+a14);
  a15=(a5+a15);
  if (res[0]!=0) res[0][59]=a15;
  if (res[0]!=0) res[0][60]=a1;
  if (res[0]!=0) res[0][61]=a1;
  if (res[0]!=0) res[0][62]=a1;
  if (res[0]!=0) res[0][63]=a1;
  if (res[0]!=0) res[0][64]=a1;
  if (res[0]!=0) res[0][65]=a0;
  if (res[0]!=0) res[0][66]=a1;
  if (res[0]!=0) res[0][67]=a1;
  if (res[0]!=0) res[0][68]=a1;
  if (res[0]!=0) res[0][69]=a1;
  a15=(a2*a7);
  a16=sin(a15);
  a16=(a2*a16);
  a17=(a6*a16);
  a18=(a2*a7);
  a19=cos(a18);
  a19=(a2*a19);
  a20=(a11*a19);
  a17=(a17+a20);
  a17=(-a17);
  if (res[0]!=0) res[0][70]=a17;
  a20=arg[2]? arg[2][3] : 0;
  a21=(a20+a20);
  a21=(a5+a21);
  if (res[0]!=0) res[0][71]=a21;
  if (res[0]!=0) res[0][72]=a3;
  if (res[0]!=0) res[0][73]=a1;
  if (res[0]!=0) res[0][74]=a1;
  if (res[0]!=0) res[0][75]=a1;
  if (res[0]!=0) res[0][76]=a1;
  if (res[0]!=0) res[0][77]=a1;
  if (res[0]!=0) res[0][78]=a0;
  if (res[0]!=0) res[0][79]=a1;
  if (res[0]!=0) res[0][80]=a1;
  if (res[0]!=0) res[0][81]=a1;
  a3=arg[3]? arg[3][5] : 0;
  a9=(a3*a9);
  a21=arg[3]? arg[3][4] : 0;
  a13=(a21*a13);
  a9=(a9-a13);
  if (res[0]!=0) res[0][82]=a9;
  a13=arg[2]? arg[2][4] : 0;
  a22=(a13+a13);
  a22=(a5+a22);
  if (res[0]!=0) res[0][83]=a22;
  if (res[0]!=0) res[0][84]=a4;
  if (res[0]!=0) res[0][85]=a1;
  if (res[0]!=0) res[0][86]=a1;
  if (res[0]!=0) res[0][87]=a1;
  if (res[0]!=0) res[0][88]=a1;
  if (res[0]!=0) res[0][89]=a1;
  if (res[0]!=0) res[0][90]=a1;
  if (res[0]!=0) res[0][91]=a0;
  if (res[0]!=0) res[0][92]=a1;
  if (res[0]!=0) res[0][93]=a1;
  a16=(a3*a16);
  a19=(a21*a19);
  a16=(a16+a19);
  a16=(-a16);
  if (res[0]!=0) res[0][94]=a16;
  a19=arg[2]? arg[2][5] : 0;
  a4=(a19+a19);
  a4=(a5+a4);
  if (res[0]!=0) res[0][95]=a4;
  if (res[0]!=0) res[0][96]=a1;
  if (res[0]!=0) res[0][97]=a1;
  if (res[0]!=0) res[0][98]=a1;
  if (res[0]!=0) res[0][99]=a1;
  if (res[0]!=0) res[0][100]=a1;
  if (res[0]!=0) res[0][101]=a1;
  if (res[0]!=0) res[0][102]=a1;
  if (res[0]!=0) res[0][103]=a1;
  if (res[0]!=0) res[0][104]=a0;
  if (res[0]!=0) res[0][105]=a1;
  if (res[0]!=0) res[0][106]=a1;
  a4=arg[2]? arg[2][6] : 0;
  a4=(a4+a4);
  a4=(a5+a4);
  if (res[0]!=0) res[0][107]=a4;
  if (res[0]!=0) res[0][108]=a1;
  if (res[0]!=0) res[0][109]=a1;
  if (res[0]!=0) res[0][110]=a1;
  if (res[0]!=0) res[0][111]=a1;
  if (res[0]!=0) res[0][112]=a1;
  if (res[0]!=0) res[0][113]=a1;
  if (res[0]!=0) res[0][114]=a1;
  if (res[0]!=0) res[0][115]=a1;
  if (res[0]!=0) res[0][116]=a1;
  if (res[0]!=0) res[0][117]=a0;
  if (res[0]!=0) res[0][118]=a1;
  a4=arg[2]? arg[2][7] : 0;
  a4=(a4+a4);
  a4=(a5+a4);
  if (res[0]!=0) res[0][119]=a4;
  if (res[0]!=0) res[0][120]=a1;
  if (res[0]!=0) res[0][121]=a1;
  if (res[0]!=0) res[0][122]=a1;
  if (res[0]!=0) res[0][123]=a1;
  if (res[0]!=0) res[0][124]=a10;
  if (res[0]!=0) res[0][125]=a17;
  if (res[0]!=0) res[0][126]=a9;
  if (res[0]!=0) res[0][127]=a16;
  if (res[0]!=0) res[0][128]=a1;
  if (res[0]!=0) res[0][129]=a1;
  a1=(a19*a21);
  a16=(a20*a11);
  a1=(a1+a16);
  a18=sin(a18);
  a18=(a2*a18);
  a1=(a1*a18);
  a1=(a2*a1);
  a19=(a19*a3);
  a20=(a20*a6);
  a19=(a19+a20);
  a15=cos(a15);
  a15=(a2*a15);
  a19=(a19*a15);
  a19=(a2*a19);
  a3=(a13*a3);
  a6=(a14*a6);
  a3=(a3+a6);
  a8=sin(a8);
  a8=(a2*a8);
  a3=(a3*a8);
  a3=(a2*a3);
  a19=(a19+a3);
  a1=(a1-a19);
  a13=(a13*a21);
  a14=(a14*a11);
  a13=(a13+a14);
  a12=cos(a12);
  a12=(a2*a12);
  a13=(a13*a12);
  a2=(a2*a13);
  a1=(a1-a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][130]=a0;
  a7=(a7+a7);
  a5=(a5+a7);
  if (res[0]!=0) res[0][131]=a5;
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int RSQrqtI_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtI_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtI_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int RSQrqtI_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtI_release(int mem) {
}

CASADI_SYMBOL_EXPORT void RSQrqtI_incref(void) {
}

CASADI_SYMBOL_EXPORT void RSQrqtI_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtI_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtI_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real RSQrqtI_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtI_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtI_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtI_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s5;
    case 5: return casadi_s4;
    case 6: return casadi_s2;
    case 7: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtI_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int RSQrqtI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* rqI:(i0,i1[2],i2[9],i3[0],i4[0])->(o0[11]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[1]? arg[1][0] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][1]=a0;
  a0=1.;
  a1=arg[2]? arg[2][0] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[2]? arg[2][1] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][3]=a1;
  a1=arg[2]? arg[2][2] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][4]=a1;
  a1=arg[2]? arg[2][3] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][5]=a1;
  a1=arg[2]? arg[2][4] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][6]=a1;
  a1=arg[2]? arg[2][5] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][7]=a1;
  a1=arg[2]? arg[2][6] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][8]=a1;
  a1=arg[2]? arg[2][7] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][9]=a1;
  a1=arg[2]? arg[2][8] : 0;
  a1=(a1+a1);
  a0=(a0+a1);
  if (res[0]!=0) res[0][10]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rqI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rqI_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rqI_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqI_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rqI_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqI_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rqI_incref(void) {
}

CASADI_SYMBOL_EXPORT void rqI_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rqI_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int rqI_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rqI_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqI_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqI_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqI_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqI_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rqI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* RSQrqt:(i0,i1[2],i2[9],i3[9],i4[4],i5,i6[0],i7[0])->(o0[12x11]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a3, a4, a5, a6, a7, a8, a9;
  a0=2.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  a2=1.0000000000000001e-01;
  a3=arg[3]? arg[3][6] : 0;
  a3=(a2*a3);
  if (res[0]!=0) res[0][6]=a3;
  a4=arg[3]? arg[3][7] : 0;
  a4=(a2*a4);
  if (res[0]!=0) res[0][7]=a4;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a1;
  a5=arg[1]? arg[1][0] : 0;
  a5=(a5+a5);
  if (res[0]!=0) res[0][11]=a5;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a1;
  if (res[0]!=0) res[0][19]=a1;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a1;
  if (res[0]!=0) res[0][22]=a1;
  a5=arg[1]? arg[1][1] : 0;
  a5=(a5+a5);
  if (res[0]!=0) res[0][23]=a5;
  if (res[0]!=0) res[0][24]=a1;
  if (res[0]!=0) res[0][25]=a1;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a1;
  if (res[0]!=0) res[0][28]=a1;
  if (res[0]!=0) res[0][29]=a1;
  if (res[0]!=0) res[0][30]=a1;
  if (res[0]!=0) res[0][31]=a1;
  if (res[0]!=0) res[0][32]=a1;
  if (res[0]!=0) res[0][33]=a1;
  if (res[0]!=0) res[0][34]=a1;
  a5=1.;
  a6=arg[2]? arg[2][0] : 0;
  a6=(a6+a6);
  a6=(a5+a6);
  if (res[0]!=0) res[0][35]=a6;
  if (res[0]!=0) res[0][36]=a1;
  if (res[0]!=0) res[0][37]=a1;
  if (res[0]!=0) res[0][38]=a1;
  if (res[0]!=0) res[0][39]=a0;
  if (res[0]!=0) res[0][40]=a1;
  if (res[0]!=0) res[0][41]=a1;
  if (res[0]!=0) res[0][42]=a1;
  if (res[0]!=0) res[0][43]=a1;
  if (res[0]!=0) res[0][44]=a1;
  if (res[0]!=0) res[0][45]=a1;
  if (res[0]!=0) res[0][46]=a1;
  a6=arg[2]? arg[2][1] : 0;
  a6=(a6+a6);
  a6=(a5+a6);
  if (res[0]!=0) res[0][47]=a6;
  if (res[0]!=0) res[0][48]=a1;
  if (res[0]!=0) res[0][49]=a1;
  if (res[0]!=0) res[0][50]=a1;
  if (res[0]!=0) res[0][51]=a1;
  if (res[0]!=0) res[0][52]=a0;
  if (res[0]!=0) res[0][53]=a1;
  if (res[0]!=0) res[0][54]=a1;
  if (res[0]!=0) res[0][55]=a1;
  if (res[0]!=0) res[0][56]=a1;
  if (res[0]!=0) res[0][57]=a1;
  a6=arg[3]? arg[3][3] : 0;
  a7=arg[2]? arg[2][8] : 0;
  a8=(a2*a7);
  a9=cos(a8);
  a9=(a2*a9);
  a10=(a6*a9);
  a11=arg[3]? arg[3][2] : 0;
  a12=(a2*a7);
  a13=sin(a12);
  a13=(a2*a13);
  a14=(a11*a13);
  a10=(a10-a14);
  if (res[0]!=0) res[0][58]=a10;
  a14=arg[2]? arg[2][2] : 0;
  a15=(a14+a14);
  a15=(a5+a15);
  if (res[0]!=0) res[0][59]=a15;
  if (res[0]!=0) res[0][60]=a1;
  if (res[0]!=0) res[0][61]=a1;
  if (res[0]!=0) res[0][62]=a1;
  if (res[0]!=0) res[0][63]=a1;
  if (res[0]!=0) res[0][64]=a1;
  if (res[0]!=0) res[0][65]=a0;
  if (res[0]!=0) res[0][66]=a1;
  if (res[0]!=0) res[0][67]=a1;
  if (res[0]!=0) res[0][68]=a1;
  if (res[0]!=0) res[0][69]=a1;
  a15=(a2*a7);
  a16=sin(a15);
  a16=(a2*a16);
  a17=(a6*a16);
  a18=(a2*a7);
  a19=cos(a18);
  a19=(a2*a19);
  a20=(a11*a19);
  a17=(a17+a20);
  a17=(-a17);
  if (res[0]!=0) res[0][70]=a17;
  a20=arg[2]? arg[2][3] : 0;
  a21=(a20+a20);
  a21=(a5+a21);
  if (res[0]!=0) res[0][71]=a21;
  if (res[0]!=0) res[0][72]=a3;
  if (res[0]!=0) res[0][73]=a1;
  if (res[0]!=0) res[0][74]=a1;
  if (res[0]!=0) res[0][75]=a1;
  if (res[0]!=0) res[0][76]=a1;
  if (res[0]!=0) res[0][77]=a1;
  if (res[0]!=0) res[0][78]=a0;
  if (res[0]!=0) res[0][79]=a1;
  if (res[0]!=0) res[0][80]=a1;
  if (res[0]!=0) res[0][81]=a1;
  a3=arg[3]? arg[3][5] : 0;
  a9=(a3*a9);
  a21=arg[3]? arg[3][4] : 0;
  a13=(a21*a13);
  a9=(a9-a13);
  if (res[0]!=0) res[0][82]=a9;
  a13=arg[2]? arg[2][4] : 0;
  a22=(a13+a13);
  a22=(a5+a22);
  if (res[0]!=0) res[0][83]=a22;
  if (res[0]!=0) res[0][84]=a4;
  if (res[0]!=0) res[0][85]=a1;
  if (res[0]!=0) res[0][86]=a1;
  if (res[0]!=0) res[0][87]=a1;
  if (res[0]!=0) res[0][88]=a1;
  if (res[0]!=0) res[0][89]=a1;
  if (res[0]!=0) res[0][90]=a1;
  if (res[0]!=0) res[0][91]=a0;
  if (res[0]!=0) res[0][92]=a1;
  if (res[0]!=0) res[0][93]=a1;
  a16=(a3*a16);
  a19=(a21*a19);
  a16=(a16+a19);
  a16=(-a16);
  if (res[0]!=0) res[0][94]=a16;
  a19=arg[2]? arg[2][5] : 0;
  a4=(a19+a19);
  a4=(a5+a4);
  if (res[0]!=0) res[0][95]=a4;
  if (res[0]!=0) res[0][96]=a1;
  if (res[0]!=0) res[0][97]=a1;
  if (res[0]!=0) res[0][98]=a1;
  if (res[0]!=0) res[0][99]=a1;
  if (res[0]!=0) res[0][100]=a1;
  if (res[0]!=0) res[0][101]=a1;
  if (res[0]!=0) res[0][102]=a1;
  if (res[0]!=0) res[0][103]=a1;
  if (res[0]!=0) res[0][104]=a0;
  if (res[0]!=0) res[0][105]=a1;
  if (res[0]!=0) res[0][106]=a1;
  a4=arg[2]? arg[2][6] : 0;
  a4=(a4+a4);
  a4=(a5+a4);
  if (res[0]!=0) res[0][107]=a4;
  if (res[0]!=0) res[0][108]=a1;
  if (res[0]!=0) res[0][109]=a1;
  if (res[0]!=0) res[0][110]=a1;
  if (res[0]!=0) res[0][111]=a1;
  if (res[0]!=0) res[0][112]=a1;
  if (res[0]!=0) res[0][113]=a1;
  if (res[0]!=0) res[0][114]=a1;
  if (res[0]!=0) res[0][115]=a1;
  if (res[0]!=0) res[0][116]=a1;
  if (res[0]!=0) res[0][117]=a0;
  if (res[0]!=0) res[0][118]=a1;
  a4=arg[2]? arg[2][7] : 0;
  a4=(a4+a4);
  a4=(a5+a4);
  if (res[0]!=0) res[0][119]=a4;
  if (res[0]!=0) res[0][120]=a1;
  if (res[0]!=0) res[0][121]=a1;
  if (res[0]!=0) res[0][122]=a1;
  if (res[0]!=0) res[0][123]=a1;
  if (res[0]!=0) res[0][124]=a10;
  if (res[0]!=0) res[0][125]=a17;
  if (res[0]!=0) res[0][126]=a9;
  if (res[0]!=0) res[0][127]=a16;
  if (res[0]!=0) res[0][128]=a1;
  if (res[0]!=0) res[0][129]=a1;
  a1=(a19*a21);
  a16=(a20*a11);
  a1=(a1+a16);
  a18=sin(a18);
  a18=(a2*a18);
  a1=(a1*a18);
  a1=(a2*a1);
  a19=(a19*a3);
  a20=(a20*a6);
  a19=(a19+a20);
  a15=cos(a15);
  a15=(a2*a15);
  a19=(a19*a15);
  a19=(a2*a19);
  a3=(a13*a3);
  a6=(a14*a6);
  a3=(a3+a6);
  a8=sin(a8);
  a8=(a2*a8);
  a3=(a3*a8);
  a3=(a2*a3);
  a19=(a19+a3);
  a1=(a1-a19);
  a13=(a13*a21);
  a14=(a14*a11);
  a13=(a13+a14);
  a12=cos(a12);
  a12=(a2*a12);
  a13=(a13*a12);
  a2=(a2*a13);
  a1=(a1-a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][130]=a0;
  a7=(a7+a7);
  a5=(a5+a7);
  if (res[0]!=0) res[0][131]=a5;
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int RSQrqt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int RSQrqt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void RSQrqt_incref(void) {
}

CASADI_SYMBOL_EXPORT void RSQrqt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int RSQrqt_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int RSQrqt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real RSQrqt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s5;
    case 5: return casadi_s4;
    case 6: return casadi_s2;
    case 7: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int RSQrqt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* rqk:(i0,i1[2],i2[9],i3[0],i4[0])->(o0[11]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[1]? arg[1][0] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][1]=a0;
  a0=1.;
  a1=arg[2]? arg[2][0] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[2]? arg[2][1] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][3]=a1;
  a1=arg[2]? arg[2][2] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][4]=a1;
  a1=arg[2]? arg[2][3] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][5]=a1;
  a1=arg[2]? arg[2][4] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][6]=a1;
  a1=arg[2]? arg[2][5] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][7]=a1;
  a1=arg[2]? arg[2][6] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][8]=a1;
  a1=arg[2]? arg[2][7] : 0;
  a1=(a1+a1);
  a1=(a0+a1);
  if (res[0]!=0) res[0][9]=a1;
  a1=arg[2]? arg[2][8] : 0;
  a1=(a1+a1);
  a0=(a0+a1);
  if (res[0]!=0) res[0][10]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rqk(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rqk_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rqk_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqk_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rqk_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqk_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rqk_incref(void) {
}

CASADI_SYMBOL_EXPORT void rqk_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rqk_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int rqk_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rqk_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqk_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqk_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqk_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqk_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rqk_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* Lk:(i0,i1[2],i2[9],i3[0],i4[0])->(o0) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[2]? arg[2][0] : 0;
  a1=casadi_sq(a0);
  a2=arg[2]? arg[2][1] : 0;
  a3=casadi_sq(a2);
  a1=(a1+a3);
  a3=arg[2]? arg[2][2] : 0;
  a4=casadi_sq(a3);
  a1=(a1+a4);
  a4=arg[2]? arg[2][3] : 0;
  a5=casadi_sq(a4);
  a1=(a1+a5);
  a5=arg[2]? arg[2][4] : 0;
  a6=casadi_sq(a5);
  a1=(a1+a6);
  a6=arg[2]? arg[2][5] : 0;
  a7=casadi_sq(a6);
  a1=(a1+a7);
  a7=arg[2]? arg[2][6] : 0;
  a8=casadi_sq(a7);
  a1=(a1+a8);
  a8=arg[2]? arg[2][7] : 0;
  a9=casadi_sq(a8);
  a1=(a1+a9);
  a9=arg[2]? arg[2][8] : 0;
  a10=casadi_sq(a9);
  a1=(a1+a10);
  a0=(a0+a2);
  a0=(a0+a3);
  a0=(a0+a4);
  a0=(a0+a5);
  a0=(a0+a6);
  a0=(a0+a7);
  a0=(a0+a8);
  a0=(a0+a9);
  a1=(a1+a0);
  a0=arg[1]? arg[1][0] : 0;
  a0=casadi_sq(a0);
  a9=arg[1]? arg[1][1] : 0;
  a9=casadi_sq(a9);
  a0=(a0+a9);
  a1=(a1+a0);
  if (res[0]!=0) res[0][0]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int Lk(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Lk_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Lk_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Lk_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Lk_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Lk_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Lk_incref(void) {
}

CASADI_SYMBOL_EXPORT void Lk_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Lk_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Lk_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Lk_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Lk_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Lk_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Lk_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Lk_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Lk_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* RSQrqtF:(i0,i1[2],i2[9],i3[9],i4[4],i5,i6[0],i7[0])->(o0[10x9]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=2.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  a2=arg[2]? arg[2][0] : 0;
  a2=(a2+a2);
  if (res[0]!=0) res[0][9]=a2;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a1;
  a2=arg[2]? arg[2][1] : 0;
  a2=(a2+a2);
  if (res[0]!=0) res[0][19]=a2;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a1;
  if (res[0]!=0) res[0][22]=a0;
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a1;
  if (res[0]!=0) res[0][25]=a1;
  if (res[0]!=0) res[0][26]=a1;
  if (res[0]!=0) res[0][27]=a1;
  if (res[0]!=0) res[0][28]=a1;
  a2=arg[2]? arg[2][2] : 0;
  a2=(a2+a2);
  if (res[0]!=0) res[0][29]=a2;
  if (res[0]!=0) res[0][30]=a1;
  if (res[0]!=0) res[0][31]=a1;
  if (res[0]!=0) res[0][32]=a1;
  if (res[0]!=0) res[0][33]=a0;
  if (res[0]!=0) res[0][34]=a1;
  if (res[0]!=0) res[0][35]=a1;
  if (res[0]!=0) res[0][36]=a1;
  if (res[0]!=0) res[0][37]=a1;
  if (res[0]!=0) res[0][38]=a1;
  a2=arg[2]? arg[2][3] : 0;
  a2=(a2+a2);
  if (res[0]!=0) res[0][39]=a2;
  if (res[0]!=0) res[0][40]=a1;
  if (res[0]!=0) res[0][41]=a1;
  if (res[0]!=0) res[0][42]=a1;
  if (res[0]!=0) res[0][43]=a1;
  if (res[0]!=0) res[0][44]=a0;
  if (res[0]!=0) res[0][45]=a1;
  if (res[0]!=0) res[0][46]=a1;
  if (res[0]!=0) res[0][47]=a1;
  if (res[0]!=0) res[0][48]=a1;
  a2=arg[2]? arg[2][4] : 0;
  a2=(a2+a2);
  if (res[0]!=0) res[0][49]=a2;
  if (res[0]!=0) res[0][50]=a1;
  if (res[0]!=0) res[0][51]=a1;
  if (res[0]!=0) res[0][52]=a1;
  if (res[0]!=0) res[0][53]=a1;
  if (res[0]!=0) res[0][54]=a1;
  if (res[0]!=0) res[0][55]=a0;
  if (res[0]!=0) res[0][56]=a1;
  if (res[0]!=0) res[0][57]=a1;
  if (res[0]!=0) res[0][58]=a1;
  a2=arg[2]? arg[2][5] : 0;
  a2=(a2+a2);
  if (res[0]!=0) res[0][59]=a2;
  if (res[0]!=0) res[0][60]=a1;
  if (res[0]!=0) res[0][61]=a1;
  if (res[0]!=0) res[0][62]=a1;
  if (res[0]!=0) res[0][63]=a1;
  if (res[0]!=0) res[0][64]=a1;
  if (res[0]!=0) res[0][65]=a1;
  if (res[0]!=0) res[0][66]=a0;
  if (res[0]!=0) res[0][67]=a1;
  if (res[0]!=0) res[0][68]=a1;
  a2=arg[2]? arg[2][6] : 0;
  a2=(a2+a2);
  if (res[0]!=0) res[0][69]=a2;
  if (res[0]!=0) res[0][70]=a1;
  if (res[0]!=0) res[0][71]=a1;
  if (res[0]!=0) res[0][72]=a1;
  if (res[0]!=0) res[0][73]=a1;
  if (res[0]!=0) res[0][74]=a1;
  if (res[0]!=0) res[0][75]=a1;
  if (res[0]!=0) res[0][76]=a1;
  if (res[0]!=0) res[0][77]=a0;
  if (res[0]!=0) res[0][78]=a1;
  a2=arg[2]? arg[2][7] : 0;
  a2=(a2+a2);
  if (res[0]!=0) res[0][79]=a2;
  if (res[0]!=0) res[0][80]=a1;
  if (res[0]!=0) res[0][81]=a1;
  if (res[0]!=0) res[0][82]=a1;
  if (res[0]!=0) res[0][83]=a1;
  if (res[0]!=0) res[0][84]=a1;
  if (res[0]!=0) res[0][85]=a1;
  if (res[0]!=0) res[0][86]=a1;
  if (res[0]!=0) res[0][87]=a1;
  if (res[0]!=0) res[0][88]=a0;
  a0=arg[2]? arg[2][8] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][89]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int RSQrqtF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int RSQrqtF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int RSQrqtF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RSQrqtF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void RSQrqtF_incref(void) {
}

CASADI_SYMBOL_EXPORT void RSQrqtF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtF_n_in(void) { return 8;}

CASADI_SYMBOL_EXPORT casadi_int RSQrqtF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real RSQrqtF_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtF_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RSQrqtF_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s5;
    case 5: return casadi_s4;
    case 6: return casadi_s2;
    case 7: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RSQrqtF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int RSQrqtF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* rqF:(i0,i1[2],i2[9],i3[0],i4[0])->(o0[9]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[2]? arg[2][0] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[2]? arg[2][1] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[2]? arg[2][2] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[2]? arg[2][3] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[2]? arg[2][4] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[2]? arg[2][5] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[2]? arg[2][6] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[2]? arg[2][7] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[2]? arg[2][8] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rqF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rqF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rqF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rqF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rqF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rqF_incref(void) {
}

CASADI_SYMBOL_EXPORT void rqF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rqF_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int rqF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rqF_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqF_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rqF_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rqF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rqF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* LF:(i0,i1[2],i2[9],i3[0],i4[0])->(o0) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[2]? arg[2][0] : 0;
  a0=casadi_sq(a0);
  a1=arg[2]? arg[2][1] : 0;
  a1=casadi_sq(a1);
  a0=(a0+a1);
  a1=arg[2]? arg[2][2] : 0;
  a1=casadi_sq(a1);
  a0=(a0+a1);
  a1=arg[2]? arg[2][3] : 0;
  a1=casadi_sq(a1);
  a0=(a0+a1);
  a1=arg[2]? arg[2][4] : 0;
  a1=casadi_sq(a1);
  a0=(a0+a1);
  a1=arg[2]? arg[2][5] : 0;
  a1=casadi_sq(a1);
  a0=(a0+a1);
  a1=arg[2]? arg[2][6] : 0;
  a1=casadi_sq(a1);
  a0=(a0+a1);
  a1=arg[2]? arg[2][7] : 0;
  a1=casadi_sq(a1);
  a0=(a0+a1);
  a1=arg[2]? arg[2][8] : 0;
  a1=casadi_sq(a1);
  a0=(a0+a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int LF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f9(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int LF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int LF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void LF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int LF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void LF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void LF_incref(void) {
}

CASADI_SYMBOL_EXPORT void LF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int LF_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int LF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real LF_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* LF_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* LF_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* LF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* LF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int LF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* GgtI:(i0[2],i1[9],i2[0],i3[0])->(o0[12x4]) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a1=1.;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  a2=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][11]=a2;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a0;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a0;
  a2=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][23]=a2;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a0;
  if (res[0]!=0) res[0][28]=a0;
  if (res[0]!=0) res[0][29]=a0;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a1;
  if (res[0]!=0) res[0][33]=a0;
  if (res[0]!=0) res[0][34]=a0;
  a2=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][35]=a2;
  if (res[0]!=0) res[0][36]=a0;
  if (res[0]!=0) res[0][37]=a0;
  if (res[0]!=0) res[0][38]=a0;
  if (res[0]!=0) res[0][39]=a0;
  if (res[0]!=0) res[0][40]=a0;
  if (res[0]!=0) res[0][41]=a0;
  if (res[0]!=0) res[0][42]=a0;
  if (res[0]!=0) res[0][43]=a0;
  if (res[0]!=0) res[0][44]=a0;
  if (res[0]!=0) res[0][45]=a1;
  if (res[0]!=0) res[0][46]=a0;
  a0=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][47]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int GgtI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f10(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GgtI_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GgtI_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgtI_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GgtI_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgtI_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GgtI_incref(void) {
}

CASADI_SYMBOL_EXPORT void GgtI_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GgtI_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int GgtI_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real GgtI_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgtI_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgtI_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgtI_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s0;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgtI_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GgtI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* gI:(i0[2],i1[9],i2[0],i3[0])->(o0[4]) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][3]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gI(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f11(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int gI_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gI_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gI_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int gI_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gI_release(int mem) {
}

CASADI_SYMBOL_EXPORT void gI_incref(void) {
}

CASADI_SYMBOL_EXPORT void gI_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int gI_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int gI_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real gI_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gI_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gI_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gI_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s0;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gI_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gI_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* GgtF:(i0[2],i1[9],i2[0],i3[0])->(o0[10x4]) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  a2=arg[1]? arg[1][0] : 0;
  a3=10.;
  a2=(a2-a3);
  if (res[0]!=0) res[0][9]=a2;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a1;
  a2=arg[1]? arg[1][1] : 0;
  a2=(a2-a3);
  if (res[0]!=0) res[0][19]=a2;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a1;
  if (res[0]!=0) res[0][22]=a1;
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a1;
  if (res[0]!=0) res[0][25]=a1;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a1;
  if (res[0]!=0) res[0][28]=a1;
  a2=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][29]=a2;
  if (res[0]!=0) res[0][30]=a1;
  if (res[0]!=0) res[0][31]=a1;
  if (res[0]!=0) res[0][32]=a1;
  if (res[0]!=0) res[0][33]=a1;
  if (res[0]!=0) res[0][34]=a1;
  if (res[0]!=0) res[0][35]=a1;
  if (res[0]!=0) res[0][36]=a1;
  if (res[0]!=0) res[0][37]=a0;
  if (res[0]!=0) res[0][38]=a1;
  a1=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][39]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int GgtF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f12(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GgtF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GgtF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgtF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GgtF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GgtF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GgtF_incref(void) {
}

CASADI_SYMBOL_EXPORT void GgtF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GgtF_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int GgtF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real GgtF_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgtF_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GgtF_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgtF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s0;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GgtF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GgtF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* gF:(i0[2],i1[9],i2[0],i3[0])->(o0[4]) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[1]? arg[1][0] : 0;
  a1=10.;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][3]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gF(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f13(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int gF_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gF_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gF_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int gF_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gF_release(int mem) {
}

CASADI_SYMBOL_EXPORT void gF_incref(void) {
}

CASADI_SYMBOL_EXPORT void gF_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int gF_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int gF_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real gF_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gF_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gF_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gF_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s0;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gF_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gF_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* Ggineqt:(i0[2],i1[9],i2[0],i3[0])->(o0[12]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a0=0.;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][11]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Ggineqt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f14(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Ggineqt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Ggineqt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Ggineqt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Ggineqt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Ggineqt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Ggineqt_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ggineqt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Ggineqt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Ggineqt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Ggineqt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ggineqt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ggineqt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Ggineqt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s0;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Ggineqt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ggineqt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* gineq:(i0[2],i1[9],i2[0],i3[0])->(o0) */
static int casadi_f15(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int gineq(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f15(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int gineq_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gineq_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gineq_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int gineq_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gineq_release(int mem) {
}

CASADI_SYMBOL_EXPORT void gineq_incref(void) {
}

CASADI_SYMBOL_EXPORT void gineq_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int gineq_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int gineq_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real gineq_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gineq_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gineq_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gineq_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s0;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gineq_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gineq_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* default_stage_params:()->(o0[0]) */
static int casadi_f16(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int default_stage_params(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f16(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int default_stage_params_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int default_stage_params_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void default_stage_params_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int default_stage_params_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void default_stage_params_release(int mem) {
}

CASADI_SYMBOL_EXPORT void default_stage_params_incref(void) {
}

CASADI_SYMBOL_EXPORT void default_stage_params_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int default_stage_params_n_in(void) { return 0;}

CASADI_SYMBOL_EXPORT casadi_int default_stage_params_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real default_stage_params_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* default_stage_params_name_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* default_stage_params_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* default_stage_params_sparsity_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* default_stage_params_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int default_stage_params_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 0;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
