name: Build Documentation

on:
  push:
    branches:
      - main # Or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Use a suitable Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme

    - name: Build Docs
      run: |
        sphinx-build -b html docs/ docs/_build/html

    - name: Upload artifacts (optional)
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/_build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
