name: Build and Test Fatropy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv venv
        source venv/bin/activate
    - name: Build and install Fatropy
      run: |
        git submodule update --init --recursive
        sudo apt-get update && sudo apt-get install -y cmake
        export CMAKE_ARGS="-DBLASFEO_TARGET=X64_AUTOMATIC -DENABLE_MULTITHREADING=OFF"
        cd fatropy
        pip install .
    - name: Install Rockit and Rockit-Fatrop plugin
      run: |
        git clone https://gitlab.kuleuven.be/meco-software/rockit.git
        git clone https://gitlab.kuleuven.be/u0110259/rockit_fatrop_plugin.git ./rockit/rockit/external/fatrop
        cd rockit
        pip install .
    - name: Test Fatropy
      run: |
        git clone https://gitlab.kuleuven.be/robotgenskill/fatrop/fatrop_rockit_demo.git
        pwd
        cd fatropy/tests/
        python ../fatrop_rockit_demo/tutorial.py
        python example.py
